import {test} from 'node:test';
import assert from 'node:assert/strict';
import {allocate,column,currentMonth,googleId,latestCriteria,mappings,sectionRows,sourceLayout,validateLayout,type Sheet} from '../server/domain.js';
import {microbiologyLimit,reportIssues,resultDisplayValue,resultIssues,type Draft,type Specification,type Category} from '../shared/model.js';
function sheet(name='September 2026',c:Category='FG'):Sheet {const m=mappings[c];const rows:unknown[][]=Array.from({length:20},()=>[]);rows[m.header-1]=Array.from({length:m.end+1},()=> '');m.headers.forEach((v,i)=>rows[m.header-1][m.start+i]=v);if(c==='EM')rows[0][0]='ENVIRONMENTAL MONITORING';else rows[1][m.start]=m.title;return {name,id:7,rows,rowCount:20,merges:[m.merge,...(m.extraMerges||[])]};}
function record(s:Sheet,row:number,ml:string,c:Category='FG',name='Example sample',remarks=''){const m=mappings[c];s.rows[row-1][m.ml]=ml;s.rows[row-1][m.start+m.fields.name]=name;s.rows[row-1][m.start+m.fields.remarks]=remarks;}
const now=new Date('2026-09-23T01:00:00Z');
test('laboratory month changes at local midnight',()=>{assert.deepEqual(currentMonth(new Date('2026-09-30T16:00:00Z'),'Asia/Manila'),{year:2026,month:10});});
test('never writes into a previous month',()=>assert.throws(()=>allocate([sheet('August 2026')],'FG',now,'Asia/Manila'),/current-month/));
test('ML-only placeholders are not samples',()=>{const s=sheet();record(s,6,'ML-FG-26-9999','FG','');assert.equal(sectionRows(s,'FG')[0].occupied,false);});
test('fills next placeholder after latest record, leaving earlier holes',()=>{const s=sheet();record(s,6,'ML-FG-26-0001','FG','');record(s,7,'ML-FG-26-0002');record(s,8,'ML-FG-26-0003','FG','');const a=allocate([s],'FG',now,'Asia/Manila');assert.equal(a.row,8);assert.equal(a.ml,'ML-FG-26-0003');assert.equal(a.range,'V8:AO8');});
test('reserved rows count toward last row and sequence',()=>{const s=sheet();record(s,6,'ML-FG-26-0001');record(s,7,'ML-FG-26-0002','FG','','RESERVED');assert.equal(allocate([s],'FG',now,'Asia/Manila').row,8);assert.equal(allocate([s],'FG',now,'Asia/Manila').ml,'ML-FG-26-0003');});
test('partially completed records cannot be overwritten',()=>{const s=sheet();record(s,6,'ML-FG-26-0001','FG','');s.rows[5][mappings.FG.start+mappings.FG.fields.received]='2026-09-23';assert.equal(allocate([s],'FG',now,'Asia/Manila').row,7);});
test('annual sequence includes prior months without appending to them',()=>{const previous=sheet('August 2026');record(previous,6,'ML-FG-26-0042');const current=sheet();const a=allocate([previous,current],'FG',now,'Asia/Manila');assert.equal(a.sheet.name,'September 2026');assert.equal(a.ml,'ML-FG-26-0043');assert.equal(a.row,4);});
test('annual reset ignores prior year',()=>{const previous=sheet('December 2025');record(previous,6,'ML-FG-25-0999');const s=sheet('January 2026');assert.equal(allocate([previous,s],'FG',new Date('2026-01-01T01:00Z'),'Asia/Manila').ml,'ML-FG-26-0001');});
test('placeholder disagreement requires reconciliation',()=>{const s=sheet();record(s,4,'ML-FG-26-0042','FG','');assert.throws(()=>allocate([s],'FG',now,'Asia/Manila'),/Placeholder/);});
test('pending server reservations participate in numbering',()=>assert.equal(allocate([sheet()],'FG',now,'Asia/Manila',['ML-FG-26-0001']).ml,'ML-FG-26-0002'));
test('old pending reservations do not block a new annual series',()=>assert.equal(allocate([sheet()],'FG',now,'Asia/Manila',['ML-FG-25-0999']).ml,'ML-FG-26-0001'));
test('used duplicates stop numbering instead of silently merging',()=>{const s=sheet();record(s,6,'ML-FG-26-0001');record(s,7,'ML-FG-26-0001');assert.throws(()=>allocate([s],'FG',now,'Asia/Manila'),/Duplicate/);});
test('neighboring categories are independent',()=>{const s=sheet();s.rows[12][0]='Unrelated SFG';s.rows[12][5]='ML-SFG-26-0999';assert.equal(allocate([s],'FG',now,'Asia/Manila').row,4);assert.equal(s.rows[12][0],'Unrelated SFG');});
test('changed headers block reads and writes',()=>{const s=sheet();s.rows[mappings.FG.header-1][mappings.FG.ml]='Renamed ML';assert.throws(()=>validateLayout(s,'FG'),/header/);});
test('date and received headers accept both historical spellings',()=>{const s=sheet('October 2026','SFG');s.rows[2][0]='Date Recieved';s.rows[2][13]='RECIEVED BY';assert.doesNotThrow(()=>validateLayout(s,'SFG'));const e=sheet('October (ENVI) 2026','EM');e.rows[3][11]='RECIEVED BY';assert.doesNotThrow(()=>validateLayout(e,'EM'));});
test('changed merged boundaries block reads and writes',()=>{const s=sheet();s.merges=[];assert.throws(()=>validateLayout(s,'FG'),/boundary/);});
test('semi-finished goods uses the current 20-column logbook section',()=>{const s=sheet('October 2026','SFG');validateLayout(s,'SFG');assert.equal(mappings.SFG.header,3);assert.equal(mappings.SFG.first,4);assert.equal(mappings.SFG.fields.sampleNameSuffix,2);assert.equal(mappings.SFG.fields.batchSize,4);assert.equal(mappings.SFG.fields.manufactureDate,6);assert.equal(mappings.SFG.fields.expiryDate,7);assert.equal(mappings.SFG.fields.ml,12);assert.equal(allocate([s],'SFG',new Date('2026-10-05T02:00:00Z'),'Asia/Manila').range,'A4:T4');});
test('incoming sections match the current October 2026 source columns and rows',()=>{for(const c of ['SFG','FG','WS','RM','ST','MIS'] as Category[])assert.doesNotThrow(()=>validateLayout(sheet('October 2026',c),c));assert.deepEqual([mappings.FG.start,mappings.FG.end,mappings.FG.ml,mappings.FG.header,mappings.FG.first],[21,40,33,3,4]);assert.deepEqual([mappings.WS.start,mappings.RM.start,mappings.ST.start,mappings.MIS.start],[43,61,81,101]);});
test('all current intake sections fit the incoming workbook read width through DO',()=>assert.equal(column(Math.max(...Object.values(mappings).filter(m=>m.title!=='ENVIRONMENTAL MONITORING').map(m=>m.end))),'DO'));
test('older monthly tabs resolve their own per-category columns and received spellings',()=>{
 const definitions:[Category,number,string,string[]][]=[
  ['SFG',0,'Semi-Finished Goods',['Date Recieved','Sample Name','Batch No.','Category','','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']],
  ['FG',14,'Finished Goods',['Date Recieved','Sample Name','Batch No.','Category','','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']],
  ['WS',29,'Water',['Date Recieve','Sample Name','Batch No.','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']],
  ['RM',41,'Raw Material',['Date Recieve','Sample Name','Batch No.','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']],
  ['ST',53,'Stability',['Date Recieve','Sample Name','','Batch No.','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']],
  ['MIS',66,'Miscellaneous',['Date Recieve','Sample Name','Batch No.','ML Number','RECIEVED BY','ANALYZED BY','DATE ANALYZED','PROCEED BY / READ BY','DATE RELEASED','STATUS','REMARKS']]
 ];
 const rows:unknown[][]=Array.from({length:12},()=>[]);for(const [category,start,title,headers] of definitions){rows[1][start]=title;headers.forEach((value,index)=>rows[4][start+index]=value);rows[5][start]='09/05/2026 @ 09:00 am';rows[5][start+1]=`${category} historical sample`;}
 const old:Sheet={id:9,name:'September 2026',rows,rowCount:12,merges:[]};
 for(const [category] of definitions){const layout=sourceLayout(old,category,undefined,new Date('2026-10-05T00:00:00Z'),'Asia/Manila');const record=sectionRows(old,category,undefined,layout).find(row=>row.row===6)!;assert.equal(layout.header,5);assert.equal(layout.first,6);assert.equal(layout.fields.name,1);assert.equal(record.occupied,true);}
 const sfg=sourceLayout(old,'SFG',undefined,new Date('2026-10-05T00:00:00Z'),'Asia/Manila');assert.equal(sfg.fields.secondaryCategory,4);
 const stability=sourceLayout(old,'ST',undefined,new Date('2026-10-05T00:00:00Z'),'Asia/Manila');assert.equal(stability.fields.context,2);
 const current=sheet('October 2026','SFG');rows[5][sfg.fields.ml]='ML-SFG-26-0221';rows[5][sfg.fields.batch]='EYI72';const allocated=allocate([old,current],'SFG',new Date('2026-10-05T00:00:00Z'),'Asia/Manila');assert.equal(allocated.ml,'ML-SFG-26-0222');assert.equal(allocated.row,4);
});
test('prefilled Water defaults do not count as a sample or block the next logger row',()=>{const s=sheet('October 2026','WS');const m=mappings.WS;s.rows[m.first-1][m.start+m.fields.fillVolume]='235 mL';s.rows[m.first-1][m.start+m.fields.manufactureDate]='N/A';s.rows[m.first-1][m.start+m.fields.expiryDate]='N/A';assert.equal(sectionRows(s,'WS')[0].occupied,false);const next=allocate([s],'WS',new Date('2026-10-05T00:00:00Z'),'Asia/Manila');assert.equal(next.row,4);assert.equal(next.range,'AR4:BH4');});
test('reviewed historical section titles remain exact and accepted',()=>{const s=sheet();s.rows[1][mappings.FG.start]='Finished Goods ';const type={id:'FG',name:'Finished Goods',active:true,order:1,register:'incoming' as const,fields:[],layout:{...mappings.FG,acceptedTitles:['Finished Goods'],extraMerges:[]},numbering:{prefix:'ML-FG',separator:'-' as const,yearDigits:2 as const,padding:4},legacyNumbering:[],applicability:'spreadsheet' as const,applicabilitySheet:'RM/FP/AS'};assert.doesNotThrow(()=>validateLayout(s,'FG',type));s.rows[1][mappings.FG.start]='Unreviewed title';assert.throws(()=>validateLayout(s,'FG',type),/section title/);});
test('environmental summary is not a sample',()=>{const s=sheet('September(ENVI) 2026','EM');record(s,5,'ML-EM-26-0001','EM');s.rows[10][1]='REPORTS GENERATED';s.rows[15][3]='.';assert.equal(sectionRows(s,'EM').length,6);assert.equal(allocate([s],'EM',now,'Asia/Manila').row,6);});
test('Google link parsing rejects foreign hosts',()=>{assert.throws(()=>googleId('https://evil.example/spreadsheets/d/abc'));assert.equal(googleId('https://docs.google.com/spreadsheets/d/abc_123/edit#gid=5'),'abc_123');});
function spec(date:string,criterion:string,context='Routine'):Specification{return {id:date,product:'Example',category:'FG',context,source:'report',revision:date,issues:[],tests:[{test:'SPC',label:'SPC',type:'numeric',unit:'cfu/g',criterion,source:'report',sourceLocation:'cell',date,dateBasis:'release',revision:date}]};}
test('latest criteria stay within exact product and context',()=>{const r=latestCriteria([spec('2025-01-01','Nmt 100'),spec('2026-01-01','Nmt 50'),spec('2026-09-01','Nmt 1','Accelerated')],'Example','FG','Routine',['SPC']);assert.equal(r[0].criterion,'Nmt 50');});
test('equally dated conflicting criteria are blocked',()=>assert.throws(()=>latestCriteria([spec('2026-01-01','Nmt 50'),spec('2026-01-01','Nmt 100')],'Example','FG','Routine',['SPC']),/disagree/));
test('missing dates block a specification match',()=>assert.throws(()=>latestCriteria([spec('','Nmt 50')],'Example','FG','Routine',['SPC']),/date/));
test('missing applicable tests cannot silently disappear',()=>assert.throws(()=>latestCriteria([spec('2026-01-01','Nmt 50')],'Example','FG','Routine',['MY']),/date/));
function draft():Draft{return {id:'d',sampleId:'s',sample:{} as any,templateId:'t',templateRevision:'1',revision:1,analyst:'A',updatedAt:'',specification:spec('2026-01-01','Nmt 50'),fields:{analysisDate:'2026-01-01',logbook:'MIC-1'},results:[{test:'SPC',state:'entered',value:'0',qualifier:'',unit:'cfu/g',reason:'',remarks:''}]};}
test('actual zero is valid while missing value is not',()=>{const d=draft();assert.deepEqual(reportIssues(d),[]);d.results[0].value='';assert.match(reportIssues(d).join(),/number/);});
test('manufacture and expiry accept full or month-only dates and compare calendar ranges',()=>{
 for(const [manufacture,expiry] of [['12/2025','01/2026'],['10/01/2026','10/2026'],['10/2026','10/01/2026'],['02/29/2024','03/2024'],['2026-10-01','11/2026']]){
  const d=draft();d.fields.manufactureDate=manufacture;d.fields.expiryDate=expiry;assert.deepEqual(reportIssues(d),[],`${manufacture} to ${expiry}`);
 }
 for(const value of ['13/2026','00/2026','02/29/2026','04/31/2026','10/26']){const d=draft();d.fields.manufactureDate=value;assert.match(reportIssues(d).join(),/Manufacture date/);}
 for(const [manufacture,expiry] of [['01/2026','12/2025'],['10/20/2026','10/19/2026'],['11/2026','10/31/2026']]){const d=draft();d.fields.manufactureDate=manufacture;d.fields.expiryDate=expiry;assert.match(reportIssues(d).join(),/earlier/);}
 const alias=draft();alias.fields['date.mfd']='10/2026';alias.fields['exp.date']='11/2026';assert.deepEqual(reportIssues(alias),[]);alias.fields['exp.date']='13/2026';assert.match(reportIssues(alias).join(),/Expiry date/);
 const analysis=draft();analysis.fields.analysisDate='10/2026';assert.match(reportIssues(analysis).join(),/Analysis date/);
});
test('partial Results imports require entry only for the missing test',()=>{const d=draft();d.specification.tests.push({...d.specification.tests[0],test:'MY',label:'Molds and Yeast'});d.results.push({...d.results[0],test:'MY',state:'not_entered',value:'',sourceValue:undefined});assert.deepEqual(resultIssues(d),['Molds and Yeast: result required']);});
test('complete Results imports do not require manual result entry',()=>{const d=draft();d.results[0].sourceValue='0';assert.deepEqual(resultIssues(d),[]);});
test('manual microbiology values use the pinned criterion and unit',()=>{const d=draft();const criterion=d.specification.tests[0];assert.equal(microbiologyLimit(criterion.test,criterion.criterion),'Nmt 50');d.results[0].value='5';assert.equal(resultDisplayValue(criterion,d.results[0]),'5 cfu/g');});
test('environmental SPC and MY long-form limits use the same fixed-limit entry and pinned units',()=>{for(const [test,limit] of [['SPC','100'],['MY','30']]){const d=draft();const t=d.specification.tests[0];t.test=test;t.criterion=`Not more than ${limit} cfu/mL`;t.unit='cfu/mL';const r=d.results[0];r.test=test;r.unit=t.unit;r.qualifier='Nmt';r.value='';assert.equal(microbiologyLimit(test,t.criterion),t.criterion);assert.equal(resultDisplayValue(t,r),t.criterion);assert.deepEqual(resultIssues(d),[]);r.qualifier='';assert.match(resultIssues(d).join(),/number/);r.value='0';assert.equal(resultDisplayValue(t,r),'0 cfu/mL');assert.deepEqual(resultIssues(d),[]);}assert.equal(microbiologyLimit('ACCUPOINT','Not more than 100 RLU'),undefined);});
test('not-tested result does not satisfy a required test',()=>{const d=draft();d.results[0].state='not_tested';d.results[0].reason='Insufficient sample';assert.match(reportIssues(d).join(),/required/);});
test('numeric unit mismatch blocks generation',()=>{const d=draft();d.results[0].unit='cfu/mL';assert.match(reportIssues(d).join(),/unit/);});
test('negative finding is distinct from not entered',()=>{const d=draft();d.specification.tests[0].type='finding';d.specification.tests[0].unit='';d.results[0].unit='';d.results[0].value='Negative';assert.deepEqual(reportIssues(d),[]);d.results[0].state='not_entered';assert.match(reportIssues(d).join(),/required/);});
test('container instances each require their own observation',()=>{const d=draft();d.specification.tests.push({...d.specification.tests[0],location:'Bottle 2'});assert.match(reportIssues(d).join(),/Bottle 2/);});
