import {randomBytes,createHash} from 'node:crypto';
import type {Request,Response,NextFunction} from 'express';
import {OAuth2Client} from 'google-auth-library';
import {db,demo,audit} from './db.js';
import {Fault} from './domain.js';
import type {User,Role} from '../shared/model.js';
declare global {namespace Express {interface Request {user:User}}}
export const oauth=new OAuth2Client(process.env.GOOGLE_CLIENT_ID,process.env.GOOGLE_CLIENT_SECRET,process.env.GOOGLE_REDIRECT_URI);
const digest=(token:string)=>createHash('sha256').update(token).digest('hex');
const cookieOptions={httpOnly:true,sameSite:'lax' as const,secure:process.env.NODE_ENV==='production',path:'/'};
export function beginAuth(_req:Request,res:Response){if(!process.env.GOOGLE_CLIENT_ID)throw new Fault(503,'Google sign-in is not configured on the server');const state=randomBytes(32).toString('hex');res.cookie('ipi_oauth',state,{...cookieOptions,maxAge:600000});res.redirect(oauth.generateAuthUrl({scope:['openid','email','profile'],state,prompt:'select_account'}));}
export async function finishAuth(req:Request,res:Response){if(!req.cookies.ipi_oauth||req.query.state!==req.cookies.ipi_oauth||typeof req.query.code!=='string')throw new Fault(403,'Invalid sign-in state');res.clearCookie('ipi_oauth',cookieOptions);const {tokens}=await oauth.getToken(req.query.code);const ticket=await oauth.verifyIdToken({idToken:tokens.id_token!,audience:process.env.GOOGLE_CLIENT_ID});const p=ticket.getPayload();if(!p?.email||!p.email_verified)throw new Fault(403,'Verified email required');const u=(await db.query('SELECT * FROM users WHERE email=$1 AND active=true',[p.email.toLowerCase()])).rows[0];if(!u)throw new Fault(403,'Your account is not on the workspace allowlist');const token=randomBytes(32).toString('hex');await db.query('INSERT INTO sessions(token_hash,email,expires_at) VALUES($1,$2,$3)',[digest(token),u.email,new Date(Date.now()+8*3600000).toISOString()]);res.cookie('ipi_session',token,{...cookieOptions,maxAge:8*3600000});await audit(u.email,'sign_in',u.email);res.redirect(process.env.APP_ORIGIN||'http://localhost:5173');}
export async function authenticate(req:Request,_res:Response,next:NextFunction){if(demo){req.user={email:'analyst@example.test',name:'Demo Analyst',role:'administrator'};return next();}const token=req.cookies.ipi_session;if(!token)throw new Fault(401,'Sign in to access the workspace');const u=(await db.query('SELECT u.* FROM sessions s JOIN users u ON u.email=s.email WHERE s.token_hash=$1 AND s.expires_at>now() AND u.active=true',[digest(token)])).rows[0];if(!u)throw new Fault(401,'Your session expired or access was removed');req.user={email:u.email,name:u.name,role:u.role};next();}
export const requireRole=(...roles:Role[])=>(req:Request,_res:Response,next:NextFunction)=>{if(!roles.includes(req.user.role))throw new Fault(403,'This action is not permitted for your role');next();};
export function sameOrigin(req:Request,_res:Response,next:NextFunction){if(['POST','PUT','PATCH','DELETE'].includes(req.method)){const origin=req.headers.origin;const expected=process.env.APP_ORIGIN||'http://localhost:5173';const allowed=new Set([expected]);if(demo)allowed.add('http://127.0.0.1:5173');if(!origin||!allowed.has(origin))throw new Fault(403,'A same-origin browser request is required');}next();}
export async function signOut(req:Request,res:Response){if(req.cookies.ipi_session)await db.query('DELETE FROM sessions WHERE token_hash=$1',[digest(req.cookies.ipi_session)]);res.clearCookie('ipi_session',cookieOptions);res.json({ok:true});}
