import {getConfiguration} from './configuration.js';
import {GoogleAuth} from 'google-auth-library';
import {Fault,googleId,column,monthOf,type Sheet} from './domain.js';
import {demo} from './db.js';
const auth=new GoogleAuth({scopes:['https://www.googleapis.com/auth/spreadsheets','https://www.googleapis.com/auth/drive.readonly']});
export async function google<T=any>(url:string,method='GET',data?:unknown):Promise<T>{if(demo)throw new Fault(400,'Google access is disabled in the de-identified demo');try{const client=await auth.getClient();return (await client.request<T>({url,method:method as any,data,timeout:30000})).data;}catch(e:any){throw new Fault(502,`Google request failed (${e.response?.status||'connection'}). Check server credentials and file access.`);}}
export async function readWorkbook(url:string):Promise<{id:string;title:string;sheets:Sheet[]}>{const id=googleId(url);const meta=await google<any>(`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=spreadsheetId,properties(title),sheets(properties,merges)`);const sheets:Sheet[]=[];
 for(const s of meta.sheets){if(!monthOf(s.properties.title))continue;if(s.properties.gridProperties.rowCount>5000)throw new Fault(409,'Monthly sheet exceeds the reviewed 5,000-row limit');const range=`'${s.properties.title.replaceAll("'","''")}'!A1:CW${s.properties.gridProperties.rowCount}`;const data=await google<any>(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(range)}?valueRenderOption=FORMATTED_VALUE`);sheets.push({id:s.properties.sheetId,name:s.properties.title,rowCount:s.properties.gridProperties.rowCount,rows:data.values||[],merges:(s.merges||[]).map((m:any)=>`${column(m.startColumnIndex||0)}${(m.startRowIndex||0)+1}:${column(m.endColumnIndex-1)}${m.endRowIndex}`)});}
 if(!sheets.length)throw new Fault(409,'No recognized monthly logbook tabs found');return {id,title:meta.properties.title,sheets};}
export async function rangeValues(id:string,sheet:string,range:string){const a1=`'${sheet.replaceAll("'","''")}'!${range}`;return (await google<any>(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(a1)}?valueRenderOption=FORMATTED_VALUE`)).values?.[0]||[];}
export async function writeRange(id:string,sheet:string,range:string,values:unknown[]){const a1=`'${sheet.replaceAll("'","''")}'!${range}`;return google(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(a1)}?valueInputOption=RAW`,'PUT',{range:a1,majorDimension:'ROWS',values:[values]});}
export async function readApplicability(url:string){const id=googleId(url);const meta=await google<any>(`https://sheets.googleapis.com/v4/spreadsheets/${id}?fields=sheets(properties(title))`);const out:{sheet:string;row:number;product:string;tests:string[]}[]=[];const config=(await getConfiguration()).value;const tests=config.tests.filter(t=>t.sheetHeader&&t.sheetColumn!=null).sort((a,b)=>a.sheetColumn!-b.sheetColumn!);for(const name of [...new Set(config.sampleTypes.filter(t=>t.applicability==='spreadsheet').map(t=>t.applicabilitySheet))]){if(!meta.sheets.some((s:any)=>s.properties.title===name))throw new Fault(409,`Missing ${name} specification tab`);const a1=`'${name.replaceAll("'","''")}'!A1:${column(Math.max(1,...tests.map(t=>t.sheetColumn!)))}2000`;const data=await google<any>(`https://sheets.googleapis.com/v4/spreadsheets/${id}/values/${encodeURIComponent(a1)}?valueRenderOption=UNFORMATTED_VALUE`);const rows=data.values||[];if(tests.some(t=>String(rows[1]?.[t.sheetColumn!]||'').trim()!==t.sheetHeader))throw new Fault(409,`${name}: applicability headers changed`);for(let i=2;i<rows.length;i++){if(!rows[i][0])continue;if(rows[i].slice(1).every((v:any)=>v==null||v===''))continue;if(tests.map(t=>rows[i][t.sheetColumn!]).some(v=>typeof v!=='boolean'))throw new Fault(409,`${name} row ${i+1}: invalid applicability value`);out.push({sheet:name,row:i+1,product:rows[i][0],tests:tests.filter(t=>rows[i][t.sheetColumn!]===true).map(t=>t.id)});}}return out;}
