import {getConfiguration,sourceTypes} from './configuration.js';
import {type SampleType,formatNumber,validateIntake} from '../shared/configuration.js';
import {randomUUID} from 'node:crypto';
import {db,locked,setting,setSetting,audit,demo} from './db.js';
import {readWorkbook,rangeValues,writeRange,readApplicability} from './google.js';
import {allocate,Fault,hash,mappings,validateLayout,sectionRows,column,type Sheet} from './domain.js';
import {categories,type Category,type Sample,type Source} from '../shared/model.js';
export interface Connections {incoming:string;environmental:string;specifications:string;folders:string[];timezone:string;reservationsReconciled:boolean;manualIntakeCoordinated:boolean;writesEnabled:boolean}
export const defaultConnections:Connections={incoming:'',environmental:'',specifications:'',folders:[],timezone:'Asia/Manila',reservationsReconciled:false,manualIntakeCoordinated:false,writesEnabled:false};
export function sourceSample(book:string,sheet:Sheet,c:Category,row:number,values:unknown[],type?:SampleType,revision?:number):Sample{const m=type?.layout||mappings[c],fields=Object.fromEntries(Object.entries(m.fields).map(([name,i])=>[name,String(values[i]??'')]));const range=`${column(m.start)}${row}:${column(m.end)}${row}`;const source:Source={spreadsheetId:book,sheetId:sheet.id,sheet:sheet.name,section:type?.name||categories[c],row,range,fingerprint:hash(values),observedAt:new Date().toISOString(),url:`https://docs.google.com/spreadsheets/d/${book}/edit#gid=${sheet.id}&range=${range}`,mappingRevision:revision?String(revision):'ipi-2026-v1',raw:values,active:true};return {id:randomUUID(),configurationRevision:revision,categoryLabel:type?.name||categories[c],category:c,ml:fields.ml,name:fields.name,batch:fields.batch,received:fields.received,status:fields.status,remarks:fields.remarks,context:fields.context||'',fields,source};}
async function saveSnapshot(s:Sample){const key=[s.source.spreadsheetId,s.source.sheetId,s.category,s.source.row].join(':');const old=(await db.query('SELECT id,data FROM samples WHERE source_key=$1',[key])).rows[0];if(old&&old.data.ml!==s.ml)throw new Fault(409,`${s.source.sheet} row ${s.source.row}: record moved or replaced; reconcile source identity`);if(old){s.id=old.id;s.fields={...old.data.fields,...s.fields};if(old.data.source.fingerprint!==s.source.fingerprint)await db.query('INSERT INTO source_history(id,sample_id,data) VALUES($1,$2,$3)',[randomUUID(),s.id,JSON.stringify(old.data.source)]);}await db.query('INSERT INTO samples(id,source_key,data) VALUES($1,$2,$3) ON CONFLICT(source_key) DO UPDATE SET data=$3,updated_at=now()',[s.id,key,JSON.stringify(s)]);return s;}
export async function syncSources(actor:string){if(demo)return {count:0,message:'De-identified demo; live synchronization is disabled'};const config=await setting('connections',defaultConnections);const managed=await getConfiguration();const sourceCatalog=await sourceTypes();let count=0;
 for(const [url,cs] of [[config.incoming,sourceCatalog.filter(t=>t.register==='incoming').map(t=>t.id)],[config.environmental,sourceCatalog.filter(t=>t.register==='environmental').map(t=>t.id)]] as [string,Category[]][]){if(!url)continue;const book=await readWorkbook(url);await locked(book.id,async()=>{const records:Sample[]=[];for(const sheet of book.sheets)for(const c of cs){const type=managed.value.sampleTypes.find(t=>t.id===c)!;validateLayout(sheet,c,type);for(const r of sectionRows(sheet,c,type))if(r.occupied&&!r.reserved)records.push(sourceSample(book.id,sheet,c,r.row,r.values,type,managed.revision));}
  // Validate identity for the entire import before persisting any changed rows.
  const existing=(await db.query('SELECT id,data FROM samples WHERE data->\'source\'->>\'spreadsheetId\'=$1',[book.id])).rows;
  for(const old of existing){const current=records.find(s=>s.source.sheetId===old.data.source.sheetId&&s.category===old.data.category&&s.source.row===old.data.source.row);if(!current||current.ml!==old.data.ml)throw new Fault(409,'A source record moved, disappeared or changed ML identity. Reconcile before synchronization.');}
  for(const record of records){await saveSnapshot(record);count++;}
 });}
 if(config.specifications)await setSetting('applicability',await readApplicability(config.specifications));
 await setSetting('sync',{lastSuccess:new Date().toISOString(),count,error:null});await audit(actor,'synchronize','sources',{count});return {count};
}
export async function submitSample(actor:string,input:{submissionId:string;category:Category;fields:Record<string,string>}){const managed=await getConfiguration();const type=managed.value.sampleTypes.find(t=>t.id===input.category);if(!type?.active)throw new Fault(400,'Choose an active sample type');const issues=validateIntake(type,input.fields,managed.value);if(issues.length)throw new Fault(400,issues.join('; '));if(demo)return submitDemo(actor,input,type,managed.revision,managed.value.general.timezone);const config=await setting('connections',defaultConnections);if(!config.writesEnabled||!config.reservationsReconciled||!config.manualIntakeCoordinated)throw new Fault(409,'An administrator must validate connections, reconcile reservations and coordinate manual intake before enabling writes');const url=type.register==='environmental'?config.environmental:config.incoming;if(!url)throw new Fault(409,'Configure the logbook connection first');const payloadHash=hash(input);const book=await readWorkbook(url);
 return locked(book.id,async()=>{const old=(await db.query('SELECT * FROM submissions WHERE id=$1',[input.submissionId])).rows[0];if(old){if(old.payload_hash!==payloadHash)throw new Fault(409,'Submission ID was already used with different values');if(old.state==='complete')return old.data.sample;throw new Fault(409,'This submission requires reconciliation; it will not be sent again automatically');}
  const pending=(await db.query('SELECT ml FROM submissions WHERE workbook=$1 AND category=$2 AND state<>\'complete\' AND ml IS NOT NULL',[book.id,input.category])).rows.map(r=>r.ml);
  const fresh=await readWorkbook(url);const target=allocate(fresh.sheets,input.category,new Date(),managed.value.general.timezone,pending,type);const m=type.layout;const values=Array.from({length:m.end-m.start+1},()=>'' as unknown);for(const [key,i] of Object.entries(m.fields)){if(key==='ml')values[i]=target.ml;else if(input.fields[key]!==undefined)values[i]=input.fields[key];}values[m.fields.receivedBy]=actor;
  const read=await rangeValues(book.id,target.sheet.name,target.range);const padded=Array.from({length:values.length},(_,i)=>read[i]??'');if(hash(padded)!==hash(target.before))throw new Fault(409,'Destination changed during logging; refresh and retry');
  const intent={configurationRevision:managed.revision,type,sheet:target.sheet.name,sheetId:target.sheet.id,row:target.row,range:target.range,before:target.before,values,actor,input};await db.query('INSERT INTO submissions(id,payload_hash,workbook,category,state,ml,data) VALUES($1,$2,$3,$4,$5,$6,$7)',[input.submissionId,payloadHash,book.id,input.category,'pending',target.ml,JSON.stringify(intent)]);
  try{await writeRange(book.id,target.sheet.name,target.range,values);const observed=await rangeValues(book.id,target.sheet.name,target.range);if(hash(Array.from({length:values.length},(_,i)=>observed[i]??''))!==hash(values))throw new Error('Readback differs');const record=sourceSample(book.id,target.sheet,input.category,target.row,values,type,managed.revision);record.fields={...input.fields,...record.fields};const sample=await saveSnapshot(record);await db.query('UPDATE submissions SET state=$1,data=$2 WHERE id=$3',['complete',JSON.stringify({...intent,sample}),input.submissionId]);await audit(actor,'sample_logged',sample.id,{submissionId:input.submissionId,source:sample.source});return sample;}catch{await db.query('UPDATE submissions SET state=$1 WHERE id=$2',['uncertain',input.submissionId]);throw new Fault(409,'The write outcome is uncertain. Do not create a new submission; ask an administrator to reconcile it.');}
 });
}
export async function reconcileSubmission(id:string,actor:string){const row=(await db.query('SELECT * FROM submissions WHERE id=$1',[id])).rows[0];if(!row)throw new Fault(404,'Submission not found');return locked(row.workbook,async()=>{const current=(await db.query('SELECT * FROM submissions WHERE id=$1',[id])).rows[0];if(current.state==='complete')return current.data.sample;const intent=current.data;const values=await rangeValues(current.workbook,intent.sheet,intent.range);if(hash(Array.from({length:intent.values.length},(_,i)=>values[i]??''))!==hash(intent.values))throw new Fault(409,'Source does not exactly match the intended write; manual reconciliation is required. Number remains held.');const config=await setting('connections',defaultConnections);const book=await readWorkbook((intent.type?.register==='environmental'||current.category==='EM')?config.environmental:config.incoming);const sheet=book.sheets.find(s=>s.id===intent.sheetId);if(!sheet)throw new Fault(409,'Original sheet is missing');validateLayout(sheet,current.category,intent.type);const record=sourceSample(current.workbook,sheet,current.category,intent.row,intent.values,intent.type,intent.configurationRevision);record.fields={...intent.input.fields,...record.fields};const sample=await saveSnapshot(record);await db.query('UPDATE submissions SET state=$1,data=$2 WHERE id=$3',['complete',JSON.stringify({...intent,sample}),id]);await audit(actor,'submission_reconciled',id);return sample;});}

async function submitDemo(actor:string,input:{submissionId:string;category:string;fields:Record<string,string>},type:SampleType,revision:number,zone:string){
 return locked('demo-intake',async tx=>{
  const old=(await tx.query('SELECT * FROM submissions WHERE id=$1',[input.submissionId])).rows[0];if(old){if(old.payload_hash!==hash(input))throw new Fault(409,'This submission was already used with different values');return old.data.sample;}
  const year=Number(new Intl.DateTimeFormat('en',{timeZone:zone,year:'numeric'}).format(new Date()));const existing=(await tx.query("SELECT data FROM samples WHERE data->>'category'=$1",[type.id])).rows.map(r=>r.data);const high=Math.max(0,...existing.map(s=>String(s.ml).match(/[-/](\d{2}|\d{4})[-/](\d+)$/)).filter(m=>m&&(Number(m[1])===year||Number(m[1])===year%100)).map(m=>Number(m![2])));
  const ml=formatNumber(type.numbering,year,high+1);const id=randomUUID();const sample:Sample={id,configurationRevision:revision,categoryLabel:type.name,category:type.id,ml,name:input.fields.name,batch:input.fields.batch,received:input.fields.received,status:'',remarks:'De-identified demonstration',context:input.fields.context||'',fields:{...input.fields,receivedBy:actor},source:{spreadsheetId:'demo',sheetId:0,sheet:new Intl.DateTimeFormat('en',{timeZone:zone,month:'long',year:'numeric'}).format(new Date()),section:type.name,row:0,range:'',fingerprint:hash(input),observedAt:new Date().toISOString(),url:'',mappingRevision:String(revision),raw:[]}};
  await tx.query('BEGIN');try{await tx.query('INSERT INTO samples(id,source_key,data) VALUES($1,$2,$3)',[id,'demo:'+id,JSON.stringify(sample)]);await tx.query('INSERT INTO submissions(id,payload_hash,workbook,category,state,ml,data) VALUES($1,$2,$3,$4,$5,$6,$7)',[input.submissionId,hash(input),'demo',type.id,'complete',ml,JSON.stringify({sample})]);await tx.query('INSERT INTO audit(id,actor,action,entity,details) VALUES($1,$2,$3,$4,$5)',[randomUUID(),actor,'Logged demonstration sample',id,JSON.stringify({ml,configurationRevision:revision})]);await tx.query('COMMIT');}catch(e){await tx.query('ROLLBACK');throw e;}return sample;
 });
}
