import {randomUUID} from 'node:crypto';
import {mkdir,access,readFile} from 'node:fs/promises';
import {db,demo,setSetting,setting} from './db.js';
import {privatePath,worker} from './reports.js';
import type {Category,Sample,Specification,Template} from '../shared/model.js';
import {hash} from './domain.js';
async function seedStandardizedDemo(){if(await setting('standardizedDemoSeeded',false))return;const path='templates/demo-standardized-noted-by.docx';try{await access(privatePath(path));}catch{return;}
 const product='De-identified Product A · 100 units';const sample=(await db.query('SELECT data FROM samples WHERE id=$1',['demo-FG'])).rows[0]?.data as Sample|undefined;if(sample&&sample.name!==product)await db.query('UPDATE samples SET data=$1,updated_at=now() WHERE id=$2',[JSON.stringify({...sample,name:product}),'demo-FG']);
 const spec=(await db.query('SELECT data FROM specifications WHERE id=$1',['demo-cotton-spec'])).rows[0]?.data as Specification|undefined;if(spec&&spec.product!==product)await db.query('UPDATE specifications SET data=$1 WHERE id=$2',[JSON.stringify({...spec,product}),'demo-cotton-spec']);await setSetting('applicability',[{sheet:'RM/FP/AS',row:3,product,tests:['SPC','MY']}]);
 const content=await readFile(privatePath(path));const validation=await worker(['validate','--input',privatePath(path)]);
 const template:Template={id:'demo-standardized-template',name:'IPI archive layout · de-identified two-test copy',family:'routine',category:'FG',revision:hash(content.toString('base64')),path,verified:true,demo:true,manifest:{...validation,requiredFields:['analysisDate','batchSize','expiryDate','fillVolume','logbookReference','manufactureDate','purpose','requestedBy'],resultBindings:[{index:0,test:'SPC'},{index:1,test:'MY'}],historicalCopy:true,approvedForLiveUse:false}};
 await db.query('INSERT INTO templates(id,data) VALUES($1,$2) ON CONFLICT(id) DO UPDATE SET data=$2',[template.id,JSON.stringify(template)]);
 const old=(await db.query('SELECT data FROM templates WHERE id=$1',['demo-template'])).rows[0]?.data;if(old?.verified)await db.query('UPDATE templates SET data=$1 WHERE id=$2',[JSON.stringify({...old,name:'Retired generic development fixture',verified:false}),'demo-template']);
 for(const row of (await db.query('SELECT id,data FROM files')).rows){const f=row.data;if(f.demo&&f.templateRevision==='demo-1'&&!f.name.startsWith('Retired generic demo · '))await db.query('UPDATE files SET data=$1 WHERE id=$2',[JSON.stringify({...f,name:`Retired generic demo · ${f.name}`}),row.id]);}
 await setSetting('standardizedDemoSeeded',true);
}
export async function seed(){if(!demo){const email=process.env.ADMIN_EMAIL?.toLowerCase();if(email)await db.query('INSERT INTO users(email,name,role) VALUES($1,$2,$3) ON CONFLICT(email) DO NOTHING',[email,'Workspace administrator','administrator']);return;}
 if((await db.query('SELECT id FROM samples LIMIT 1')).rows.length){await seedStandardizedDemo();return;}
 const names=['De-identified Product A · 100 units','Botanical Sample B','Purified Water · Point 03','Base Material C','Stability Sample D','Laboratory Sample E','Production Area F'];const codes:Category[]=['FG','SFG','WS','RM','ST','MIS','EM'];
 for(let i=0;i<codes.length;i++){const c=codes[i];const id=`demo-${c}`;const sample:Sample={id,category:c,ml:`ML-${c}-26-000${i+1}`,name:names[i],batch:`DEMO-00${i+1}`,received:'2026-09-23 09:00',status:i===2?'RELEASED':'ON-GOING',remarks:'De-identified development example',context:'Routine',fields:{receivedBy:'Demo Analyst'},source:{spreadsheetId:'demo',sheetId:0,sheet:'September 2026',section:c,row:6+i,range:'',fingerprint:'demo',observedAt:new Date().toISOString(),url:'',mappingRevision:'demo',raw:[]}};await db.query('INSERT INTO samples(id,source_key,data) VALUES($1,$2,$3)',[id,id,JSON.stringify(sample)]);}
 const spec:Specification={id:'demo-cotton-spec',product:names[0],category:'FG',context:'Routine',revision:'demo-1',source:'De-identified development fixture',issues:[],tests:[{test:'SPC',label:'Standard Plate Count (SPC)',type:'numeric',unit:'cfu/g',criterion:'Nmt 50 cfu/g',source:'Development fixture — not an approved IPI specification',sourceLocation:'table 1, row 3',date:'2026-09-01',dateBasis:'release',revision:'demo-1'},{test:'MY',label:'Molds and Yeast',type:'numeric',unit:'cfu/g',criterion:'Nmt 10 cfu/g',source:'Development fixture — not an approved IPI specification',sourceLocation:'table 1, row 4',date:'2026-09-01',dateBasis:'release',revision:'demo-1'}]};await db.query('INSERT INTO specifications(id,data) VALUES($1,$2)',[spec.id,JSON.stringify(spec)]);
 await mkdir(privatePath('templates'),{recursive:true});const target=privatePath('templates/demo.docx');await worker(['demo','--output',target]);const template:Template={id:'demo-template',name:'Development report · two tests',family:'routine',category:'FG',revision:'demo-1',path:'templates/demo.docx',verified:true,demo:true,manifest:{requiredFields:['analysisDate','logbookReference']}};await db.query('INSERT INTO templates(id,data) VALUES($1,$2)',[template.id,JSON.stringify(template)]);await setSetting('applicability',[{sheet:'RM/FP/AS',row:3,product:names[0],tests:['SPC','MY']}]);await setSetting('sync',{lastSuccess:null,error:null,count:7});await seedStandardizedDemo();
}
