import Dialog from './dialog';
import AuditLog from './audit';
import {useContext,useEffect,useState} from 'react';
import {Plus,Save,Search,Settings2} from 'lucide-react';
import {api} from './api';
import {useConfiguration,useUnsaved} from './configuration';
import {PageTitle,Field,ErrorBox,Notice,Badge,Empty} from './ui';
import {configSchema,formatNumber,type Configuration,type FormField} from '../shared/configuration';
import SettingsPage from './settings';
import Specifications from './specifications';

const sections=[['general','General','Application name, laboratory, location and dates'],['sampleTypes','Sample types','Categories, availability and test applicability'],['fields','Form fields','Labels, required fields, defaults and source columns'],['products','Products / materials','Names, aliases and active products'],['tests','Tests','Manual result controls, units and report labels'],['specifications','Specifications','Applicable tests and versioned acceptance criteria'],['lookups','Lookup values','Reusable dropdown options'],['numbers','Control numbers','Prefixes and annual sequence formatting'],['reports','Report defaults','Standing signatory and document metadata'],['appearance','Appearance','Theme, density and list size'],['connections','Connections','Google logbooks and file library'],['references','Reference documents','Inspect historical reports'],['templates','Report templates','Standardized DOCX layouts'],['people','Users & permissions','Authorized accounts and roles'],['audit','Audit history','Who changed what and when']] as const;
const listKeys=['sampleTypes','products','tests','lookups'] as const;
type ListKey=typeof listKeys[number];
export default function AdminCenter(){
 const {config,reload}=useConfiguration();const [draft,setDraft]=useState<Configuration>(structuredClone(config.value)),[section,setSection]=useState('general'),[query,setQuery]=useState(''),[selected,setSelected]=useState(''),[entityQuery,setEntityQuery]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[confirm,setConfirm]=useState(false);
 const notify=useContext(Notice);const dirty=JSON.stringify(draft)!==JSON.stringify(config.value);const clearUnsaved=useUnsaved(dirty);
 useEffect(()=>setDraft(structuredClone(config.value)),[config.revision]);
 const change=(group:'general'|'reports',key:string,value:any)=>setDraft(d=>({...d,[group]:{...d[group],[key]:value}}));
 const listKey:ListKey=section==='fields'||section==='numbers'?'sampleTypes':listKeys.includes(section as ListKey)?section as ListKey:'sampleTypes';
 const items=draft[listKey];const item:any=items.find(i=>i.id===selected)||items[0];
 const edit=(key:string,value:any)=>setDraft(d=>({...d,[listKey]:d[listKey].map(i=>i.id===item.id?{...i,[key]:value}:i)}));
 const add=()=>{const id=`${listKey.slice(0,4)}-${Date.now().toString(36)}`;let next:any;
  if(listKey==='sampleTypes'){next=structuredClone(draft.sampleTypes[0]);Object.assign(next,{id,name:'New sample type',active:false,order:items.length,numbering:{...next.numbering,prefix:id.toUpperCase()},legacyNumbering:[]});}
  else if(listKey==='products')next={id,name:'New product',category:draft.sampleTypes[0].id,code:'',aliases:[],active:true};
  else if(listKey==='tests')next={id,name:'New test',shortName:'New test',reportLabel:'New test',unit:'',inputType:'numeric',active:true,order:items.length,categories:[],sheetHeader:'',sheetColumn:null};
  else next={id,name:'New lookup',options:[],active:true};
  setDraft(d=>({...d,[listKey]:[...d[listKey],next]}));setSelected(id);
 };
 const save=async()=>{setBusy(true);setError('');try{await api('/configuration','PUT',{revision:config.revision,value:draft});clearUnsaved();await reload();notify('Settings saved. New work will use this configuration.');setConfirm(false);}catch(e:any){setError(e.message);setConfirm(false);}finally{setBusy(false);}};
 return <><PageTitle title="Settings center" description="Manage your laboratory’s daily workflow without changing the application." action={<Badge>Revision {config.revision}</Badge>}/>
 <div className="settings-layout"><aside className="settings-nav"><select className="mobile-settings-select" aria-label="Settings section" value={section} onChange={e=>{setSection(e.target.value);setSelected('');setEntityQuery('');}}>{sections.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select><div className="search"><Search size={17}/><input aria-label="Search settings" placeholder="Find a setting…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{sections.filter(s=>s.join(' ').toLowerCase().includes(query.toLowerCase())).map(([id,label,hint])=><button key={id} className={section===id?'active':''} onClick={()=>{setSection(id);setSelected('');setEntityQuery('');}}><strong>{label}</strong><small>{hint}</small></button>)}</aside>
 <div className="settings-content"><ErrorBox message={error}/>{section==='audit'?<AuditLog/>:['connections','references','templates','people'].includes(section)?<SettingsPage key={section} initialTab={section} embedded/>:section==='specifications'?<Specifications/>:
 ['general','appearance','reports'].includes(section)?<section className="panel padded"><h2>{sections.find(s=>s[0]===section)?.[1]}</h2><div className="form-grid">
 {section==='general'?<>{[['appName','Application name'],['laboratoryName','Laboratory name'],['department','Department'],['site','Site / location'],['timezone','Laboratory timezone']].map(([key,label])=><Field key={key} label={label}><input value={(draft.general as any)[key]} onChange={e=>change('general',key,e.target.value)}/></Field>)}<Field label="Date display"><select value={draft.general.dateFormat} onChange={e=>change('general','dateFormat',e.target.value)}><option value="en-PH">Philippines</option><option value="en-GB">Day / month / year</option><option value="en-US">Month / day / year</option></select></Field></>:null}
 {section==='appearance'?<><Field label="Theme"><select value={draft.general.theme} onChange={e=>change('general','theme',e.target.value)}><option value="system">Follow device</option><option value="light">Light</option><option value="dark">Dark</option></select></Field><Field label="Spacing"><select value={draft.general.density} onChange={e=>change('general','density',e.target.value)}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></select></Field><Field label="Samples per page"><select value={draft.general.pageSize} onChange={e=>change('general','pageSize',Number(e.target.value))}>{[10,25,50].map(n=><option key={n}>{n}</option>)}</select></Field></>:null}
 {section==='reports'?<>{[['title','Report title'],['notedBy','Noted by — standing name'],['notedByRole','Signatory role'],['filenamePrefix','Download filename prefix'],['footer','Footer text']].map(([key,label])=><Field key={key} label={label} hint={['title','footer'].includes(key)?'Used only when the verified template contains the matching report token. Fixed form text stays unchanged.':undefined}><input value={(draft.reports as any)[key]} onChange={e=>change('reports',key,e.target.value)}/></Field>)}<p className="info">Page X of Y remains automatic. Signature and approval dates remain outside the app. Saved drafts keep their previous report settings.</p></>:null}
 </div></section>:<div className="entity-layout"><section className="panel entity-list"><div className="section-heading"><h2>{sections.find(s=>s[0]===section)?.[1]}</h2>{!['fields','numbers'].includes(section)?<button className="button secondary small" onClick={add}><Plus size={16}/> Add</button>:null}</div><input aria-label="Search configuration items" placeholder="Find an item…" value={entityQuery} onChange={e=>setEntityQuery(e.target.value)}/>{items.filter((i:any)=>`${i.name} ${i.code||''}`.toLowerCase().includes(entityQuery.toLowerCase())).map((i:any)=><button key={i.id} className={item?.id===i.id?'selected':''} onClick={()=>setSelected(i.id)}><strong>{i.name}</strong><Badge tone={i.active?'green':'neutral'}>{i.active?'Active':'Inactive'}</Badge></button>)}{!items.length?<Empty title="Nothing added yet">Use Add to create your first item.</Empty>:null}</section>
 {item?<section className="panel padded"><h2>{item.name}</h2>{section==='fields'?<FieldEditor type={item} lookups={draft.lookups} onChange={edit}/>:section==='numbers'?<><div className="info">Sequence resets annually and continues across months. Earlier gaps are never filled. Existing numbers remain recognized after a prefix change.</div><div className="form-grid"><Field label="Prefix"><input value={item.numbering.prefix} onChange={e=>edit('numbering',{...item.numbering,prefix:e.target.value})}/></Field><Field label="Year format"><select value={item.numbering.yearDigits} onChange={e=>edit('numbering',{...item.numbering,yearDigits:Number(e.target.value)})}><option value={2}>Two digits (26)</option><option value={4}>Four digits (2026)</option></select></Field><Field label="Separator"><select value={item.numbering.separator} onChange={e=>edit('numbering',{...item.numbering,separator:e.target.value})}><option>-</option><option>/</option></select></Field><Field label="Sequence digits"><input type="number" min={4} max={8} value={item.numbering.padding} onChange={e=>edit('numbering',{...item.numbering,padding:Number(e.target.value)})}/></Field></div><p className="number-preview">{formatNumber(item.numbering,2026,1)}</p></>:<><div className="form-grid"><Field label="Name"><input value={item.name} onChange={e=>edit('name',e.target.value)}/></Field><Field label="Availability"><select value={String(item.active)} onChange={e=>edit('active',e.target.value==='true')}><option value="true">Active</option><option value="false">Inactive — keep history</option></select></Field>{'order' in item?<Field label="Display order"><input type="number" min={0} value={item.order} onChange={e=>edit('order',Number(e.target.value))}/></Field>:null}
 {section==='sampleTypes'?<><Field label="Register"><select value={item.register} disabled={config.value.sampleTypes.some(t=>t.id===item.id)} onChange={e=>edit('register',e.target.value)}><option value="incoming">Incoming samples</option><option value="environmental">Environmental monitoring</option></select></Field><Field label="Applicable tests come from"><select value={item.applicability} onChange={e=>edit('applicability',e.target.value)}><option value="spreadsheet">Specifications spreadsheet</option><option value="managed">Managed specification revisions</option></select></Field>{item.applicability==='spreadsheet'?<Field label="Applicability sheet name"><input value={item.applicabilitySheet} onChange={e=>edit('applicabilitySheet',e.target.value)}/></Field>:null}</>:null}
 {section==='products'?<><Field label="Product code"><input value={item.code} onChange={e=>edit('code',e.target.value)}/></Field><Field label="Sample type"><select value={item.category} onChange={e=>edit('category',e.target.value)}>{draft.sampleTypes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field><Field label="Aliases" hint="One alternative name per line"><textarea value={item.aliases.join('\n')} onChange={e=>edit('aliases',e.target.value.split('\n'))}/></Field></>:null}
 {section==='tests'?<>{[['shortName','Short name'],['reportLabel','Report label'],['unit','Default unit'],['sheetHeader','Applicability spreadsheet header']].map(([key,label])=><Field key={key} label={label}><input value={item[key]} onChange={e=>edit(key,e.target.value)}/></Field>)}<Field label="Applicability column (B = 1)" hint="Independent of display order. Blank means this test is managed only in the app."><input type="number" min={1} max={100} value={item.sheetColumn??''} onChange={e=>edit('sheetColumn',e.target.value===''?null:Number(e.target.value))}/></Field><Field label="Manual result control"><select value={item.inputType} onChange={e=>edit('inputType',e.target.value)}><option value="numeric">Number and qualifier</option><option value="finding">Positive / negative</option></select></Field><div><h3>Available for</h3>{draft.sampleTypes.map(t=><label className="checkbox" key={t.id}><input type="checkbox" checked={item.categories.includes(t.id)} onChange={e=>edit('categories',e.target.checked?[...item.categories,t.id]:item.categories.filter((id:string)=>id!==t.id))}/>{t.name}</label>)}</div></>:null}
 {section==='lookups'?<Field label="Dropdown options" hint="One option per line"><textarea rows={8} value={item.options.join('\n')} onChange={e=>edit('options',e.target.value.split('\n'))}/></Field>:null}</div>{section==='sampleTypes'?<details className="spacing"><summary>Source layout — controlled configuration</summary><p>These settings must match the logbook exactly. Saving changes pauses live intake until connection validation succeeds.</p><div className="form-grid">{[['start','First column (A = 0)'],['end','Last column (A = 0)'],['ml','ML column (A = 0)'],['header','Header row'],['first','First data row'],['title','Merged section title'],['merge','Merged section range']].map(([key,label])=><Field key={key} label={label}><input type={typeof item.layout[key]==='number'?'number':'text'} value={item.layout[key]} onChange={e=>edit('layout',{...item.layout,[key]:typeof item.layout[key]==='number'?Number(e.target.value):e.target.value})}/></Field>)}{Object.entries(item.layout.fields).map(([key,offset])=><Field key={key} label={key.replace(/([A-Z])/g,' $1')+' — source offset'}><input type="number" min={0} max={100} value={Number(offset)} onChange={e=>{const column=Number(e.target.value);setDraft(d=>({...d,sampleTypes:d.sampleTypes.map(t=>t.id===item.id?{...t,layout:{...t.layout,fields:{...t.layout.fields,[key]:column}},fields:t.fields.map(f=>f.key===key?{...f,column}:f)}:t)}));}}/></Field>)}<Field label="Accepted historical section titles" hint="One exact reviewed title per line"><textarea value={(item.layout.acceptedTitles||[]).join('\n')} onChange={e=>edit('layout',{...item.layout,acceptedTitles:e.target.value.split('\n').filter(Boolean)})}/></Field><Field label="Column headers" hint="One per line, including blank headers"><textarea rows={8} value={item.layout.headers.join('\n')} onChange={e=>edit('layout',{...item.layout,headers:e.target.value.split('\n')})}/></Field><Field label="Additional merged ranges" hint="One per line"><textarea value={item.layout.extraMerges.join('\n')} onChange={e=>edit('layout',{...item.layout,extraMerges:e.target.value.split('\n').filter(Boolean)})}/></Field></div></details>:null}</>}</section>:null}</div>}
 {dirty?<div className="save-bar"><span>Unsaved settings · changes apply to new work</span><button className="button secondary" disabled={busy} onClick={()=>{if(window.confirm('Discard unsaved settings?'))setDraft(structuredClone(config.value));}}>Cancel</button><button className="button primary" disabled={busy} onClick={()=>{const result=configSchema.safeParse(draft);if(!result.success){setError([...new Set(result.error.issues.map(i=>i.message))].join('; '));return;}setError('');setConfirm(true);}}><Save size={17}/> Save settings</button></div>:null}</div></div>
 {confirm?<Dialog title="Apply these settings?" onClose={()=>{if(!busy)setConfirm(false);}}><p>New work will use revision {config.revision+1}. Existing results and reports retain their saved references. Changes to numbering or source layouts will pause live intake for validation.</p><div className="actions"><button autoFocus className="button secondary" disabled={busy} onClick={()=>setConfirm(false)}>Keep editing</button><button className="button primary" disabled={busy} onClick={save}>{busy?'Saving…':'Apply settings'}</button></div></Dialog>:null}</>;
}
function FieldEditor({type,lookups,onChange}:{type:any;lookups:Configuration['lookups'];onChange:(key:string,value:any)=>void}){
 const update=(index:number,key:string,value:any)=>{const fields=type.fields.map((f:FormField,i:number)=>i===index?{...f,[key]:value}:f);onChange('fields',fields);};
 return <><p>Control what an analyst sees. New unmapped fields are retained in the app; mapped fields must match the source layout.</p>{type.fields.map((f:FormField,i:number)=><details key={f.key} className="field-editor"><summary>{f.label} <Badge>{f.active?f.required?'Required':'Optional':'Inactive'}</Badge></summary><div className="form-grid"><Field label="Label"><input value={f.label} onChange={e=>update(i,'label',e.target.value)}/></Field><Field label="Field type"><select value={f.type} onChange={e=>update(i,'type',e.target.value)}>{['text','number','date','datetime-local','dropdown','checkbox','longtext','generated'].map(t=><option key={t} value={t}>{t==='datetime-local'?'Date and time':t==='generated'?'Read only / generated':t}</option>)}</select></Field><Field label="Help text"><input value={f.help} onChange={e=>update(i,'help',e.target.value)}/></Field><Field label="Default value"><input value={f.defaultValue} onChange={e=>update(i,'defaultValue',e.target.value)}/></Field><Field label="Display order"><input type="number" min={0} value={f.order} onChange={e=>update(i,'order',Number(e.target.value))}/></Field><label className="checkbox"><input type="checkbox" checked={f.required} onChange={e=>update(i,'required',e.target.checked)}/>Required</label><label className="checkbox"><input type="checkbox" checked={f.active} onChange={e=>update(i,'active',e.target.checked)}/>Active</label>{f.type==='number'?<label className="checkbox"><input type="checkbox" checked={f.integer!==false} onChange={e=>update(i,'integer',e.target.checked)}/>Whole numbers only</label>:null}{f.type==='dropdown'?<><Field label="Shared lookup"><select value={f.lookup} onChange={e=>update(i,'lookup',e.target.value)}><option value="">Use field-specific options</option>{lookups.filter(l=>l.active).map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field>{!f.lookup?<Field label="Options — one per line"><textarea value={f.options.join('\n')} onChange={e=>update(i,'options',e.target.value.split('\n'))}/></Field>:null}</>:null}</div><Field label="Storage location" hint="Use an unused source column only after updating the logbook header mapping. Blank keeps this field in the app."><input type="number" min={0} max={type.layout.end-type.layout.start} placeholder="App only" value={f.column??''} onChange={e=>{const column=e.target.value===''?null:Number(e.target.value);update(i,'column',column);const mapped={...type.layout.fields};if(column===null)delete mapped[f.key];else mapped[f.key]=column;onChange('layout',{...type.layout,fields:mapped});}}/></Field></details>)}<button className="button secondary" onClick={()=>onChange('fields',[...type.fields,{key:'field_'+Date.now().toString(36),label:'New field',type:'text',required:false,active:true,order:type.fields.length,help:'',defaultValue:'',options:[],lookup:'',column:null}])}><Plus size={16}/> Add field</button></>;
}
