import {useState} from 'react';
import {useLoad,ErrorBox,Loading,Empty} from './ui';
import {api} from './api';
function changes(before:any,after:any,prefix=''):Array<{field:string;before:string;after:string}>{
 if(JSON.stringify(before)===JSON.stringify(after))return [];
 if(before&&after&&typeof before==='object'&&typeof after==='object')return [...new Set([...Object.keys(before),...Object.keys(after)])].flatMap(k=>changes(before[k],after[k],prefix?`${prefix} › ${Array.isArray(after)?after[Number(k)]?.name||after[Number(k)]?.label||`Item ${Number(k)+1}`:k}`:k));
 const show=(v:any)=>v===undefined?'Not set':typeof v==='boolean'?v?'Yes':'No':String(v);
 return [{field:prefix.replace(/([a-z])([A-Z])/g,'$1 $2'),before:show(before),after:show(after)}];
}
export default function AuditLog(){const [q,setQ]=useState(''),[page,setPage]=useState(1);const {data,error}=useLoad<any>(()=>api('/audit-list?'+new URLSearchParams({q,page:String(page)})),[q,page]);return <section className="panel padded"><h2>Audit history</h2><p>Attributable changes to samples, reports and laboratory settings.</p><input aria-label="Search activity" placeholder="Search an action or person…" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><ErrorBox message={error}/>{!data?<Loading/>:data.items.map((a:any)=><AuditEntry key={a.id} event={a}/>)}{data?.total===0?<Empty title="No matching activity">Try a different action or account name.</Empty>:null}{data?<div className="pagination"><span>{data.total} events · Page {page} of {Math.max(1,Math.ceil(data.total/25))}</span><button className="button secondary small" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button secondary small" disabled={page*25>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div>:null}</section>;}
function AuditEntry({event:a}:{event:any}){const [detail,setDetail]=useState<any>(),[error,setError]=useState('');return <details className="history" onToggle={async e=>{if(e.currentTarget.open&&!detail){try{setDetail((await api('/audit/'+a.id)).details);}catch(e:any){setError(e.message);}}}}><summary><strong>{a.action.replaceAll('_',' ')}</strong><br/><small>{a.actor} · {new Date(a.created_at).toLocaleString()}</small></summary><ErrorBox message={error}/>{!detail?<Loading/>:detail.previous&&detail.newValue?<div className="table-scroll"><table><thead><tr><th>Changed setting</th><th>Previous value</th><th>New value</th></tr></thead><tbody>{changes(detail.previous,detail.newValue).map((d,i)=><tr key={i}><td>{d.field}</td><td>{d.before}</td><td>{d.after}</td></tr>)}</tbody></table></div>:<p>{detail.revision?`Saved revision ${detail.revision}. `:''}{detail.ml?`Control number ${detail.ml}. `:''}The action and responsible account were recorded.</p>}</details>;}
