import {useContext,useState,useEffect} from 'react';
import {useConfiguration,useUnsaved} from './configuration';
import {api,fileBase64} from './api';
import {Field,ErrorBox,Notice,useLoad,Badge} from './ui';
import type {EnvironmentalProfile,EnvironmentalOutput} from '../shared/environmental';
import type {BatchRules} from '../shared/environmental-batch';

const batchFamilies=[['environmental-grouped-5c','Grouped · 5 columns'],['environmental-gip-4c','GIP · 4 columns'],['environmental-water-4c','Water validation · 4 columns'],['environmental-warehouse-phase-air-7c','Warehouse phase/air · 7 columns']];
function EnvironmentalBatch({templates,onPublished}:{templates:any[];onPublished:()=>void}){
 const {reload:reloadConfig}=useConfiguration(),notify=useContext(Notice);
 const {data:imports,reload:reloadImports}=useLoad<any[]>(()=>api('/environmental/imports'));
 const [id,setId]=useState(''),[rules,setRules]=useState<BatchRules>({facility:'',context:'',criterionDate:'',effectiveFrom:'',createProducts:false,unchanged:true,layouts:Object.fromEntries(batchFamilies.map(([family])=>{const choices=templates.filter(t=>t.family===family&&t.active!==false&&t.verified);return [family,choices.length===1?choices[0].id:''];}))});
 const [layoutsInitialized,setLayoutsInitialized]=useState(false),[filter,setFilter]=useState('');
 useEffect(()=>{if(layoutsInitialized||!templates.length)return;setRules(previous=>({...previous,layouts:Object.fromEntries(batchFamilies.map(([family])=>{const choices=templates.filter(t=>t.family===family&&t.active!==false&&t.verified);return [family,previous.layouts[family]||(choices.length===1?choices[0].id:'')];}))}));setLayoutsInitialized(true);},[templates,layoutsInitialized]);
 const [preview,setPreview]=useState<any>(),[selected,setSelected]=useState<string[]>([]),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[results,setResults]=useState<any>(),[scanning,setScanning]=useState(false);
 function change(next:BatchRules){setRules(next);setPreview(undefined);setSelected([]);setReviewed(false);setResults(undefined);}
 async function prepare(importId=id){setBusy(true);setError('');setReviewed(false);try{const next=await api(`/environmental/imports/${importId}/preview`,'POST',rules);setScanning(next.status==='scanning');setPreview(next);setSelected(next.proposals.filter((p:any)=>!p.issues.length&&!p.published).map((p:any)=>p.key));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 useEffect(()=>{
  if(!scanning||!id)return;
  let active=true;const timer=setInterval(async()=>{try{const next=await api(`/environmental/imports/${id}/preview`,'POST',rules);if(!active)return;setPreview(next);if(next.status!=='scanning'){setScanning(false);setSelected(next.proposals.filter((p:any)=>!p.issues.length&&!p.published).map((p:any)=>p.key));}}catch(e:any){if(active){setError(e.message);setScanning(false);}}},5000);
  return()=>{active=false;clearInterval(timer);};
 },[scanning,id,rules]);
 async function upload(file:File){setBusy(true);setError('');setPreview(undefined);setResults(undefined);try{const response=await fetch('/api/environmental/imports?name='+encodeURIComponent(file.name),{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/zip'},body:file});const next=await response.json();if(!response.ok)throw new Error(next.error||'Archive processing failed');setId(next.id);reloadImports();await prepare(next.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function publish(){setBusy(true);setError('');try{const next=await api(`/environmental/imports/${id}/publish`,'POST',{rules,selected,reviewed,configurationRevision:preview.configurationRevision});setResults(next.results);setReviewed(false);setSelected([]);setPreview(undefined);onPublished();reloadConfig();notify('Bulk publication finished. Review the per-pattern outcome below.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const ready=preview?.proposals.filter((p:any)=>!p.issues.length&&!p.published)||[];
 const visible=preview?.proposals.filter((p:any)=>[p.profile.product,p.profile.area,p.profile.facility,p.profile.context,p.profile.equipmentSet,...p.issues].join(' ').toLocaleLowerCase().includes(filter.toLocaleLowerCase()))||[];
 return <details className="spacing environmental-batch"><summary>Bulk setup from environmental archive</summary><p>Upload the archive once. Repeated reports become reusable patterns; historical results are excluded. Match products and layouts automatically, confirm shared defaults once, and publish selected ready patterns together. Exceptions remain unpublished.</p>
 <div className="form-grid"><Field label="Environmental archive (.zip)"><input type="file" accept=".zip" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></Field><Field label="Resume prepared archive"><select disabled={busy} value={id} onChange={e=>{setId(e.target.value);setScanning(false);setPreview(undefined);setSelected([]);setReviewed(false);setResults(undefined);}}><option value="">Choose an archive…</option>{imports?.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>
 <Field label="Fallback facility" hint="Used only where a unique matching logbook activity cannot supply it."><input value={rules.facility} disabled={busy} onChange={e=>change({...rules,facility:e.target.value})}/></Field><Field label="Fallback testing context"><input value={rules.context} disabled={busy} onChange={e=>change({...rules,context:e.target.value})}/></Field>{!rules.unchanged?<><Field label="Confirmed criterion date for this batch"><input type="date" value={rules.criterionDate} disabled={busy} onChange={e=>change({...rules,criterionDate:e.target.value})}/></Field><Field label="Approved effective start for this batch"><input type="date" value={rules.effectiveFrom} disabled={busy} onChange={e=>change({...rules,effectiveFrom:e.target.value})}/></Field></>:null}
 {batchFamilies.map(([family,label])=><Field key={family} label={label+' layout'}><select disabled={busy} value={rules.layouts[family]||''} onChange={e=>change({...rules,layouts:{...rules.layouts,[family]:e.target.value}})}><option value="">Select an approved layout…</option>{templates.filter(t=>t.family===family&&t.active!==false&&t.verified).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>)}</div>
 <label className="checkbox spacing"><input type="checkbox" disabled={busy} checked={Boolean(rules.unchanged)} onChange={e=>change({...rules,unchanged:e.target.checked})}/>Parameters are unchanged across activity dates. Record approval today and apply these patterns to historical and current activities.</label><label className="checkbox spacing"><input type="checkbox" disabled={busy} checked={rules.createProducts} onChange={e=>change({...rules,createProducts:e.target.checked})}/>Create missing environmental products using the proposed archive names when I publish selected patterns.</label><p>If parameters changed historically, uncheck the unchanged-parameters option and supply the approved dates for that group. A location-set label is not confirmation of a physical production line.</p><button className="button secondary" disabled={busy||!id} onClick={()=>void prepare()}>{busy?'Processing archive…':'Prepare bulk patterns'}</button><ErrorBox message={error}/>
 {scanning?<p role="status">Scanning archive: {preview?.progress?.documents||0} documents processed. You can leave this page and resume the prepared archive later.</p>:null}
 {preview&&!scanning?<><p role="status">{preview.documents} documents scanned · {preview.proposals.length} proposed patterns · {ready.length} ready · {preview.exceptions.length} document exceptions.</p><label className="checkbox"><input type="checkbox" disabled={busy||!ready.length} checked={ready.length>0&&ready.every((p:any)=>selected.includes(p.key))} onChange={e=>{setSelected(e.target.checked?ready.map((p:any)=>p.key):[]);setReviewed(false);}}/>Select all ready patterns</label><Field label="Filter prepared patterns"><input value={filter} onChange={e=>setFilter(e.target.value)} placeholder="Product, area, equipment or exception…"/></Field><div className="table-scroll"><table><caption>Prepared environmental patterns and exceptions</caption><thead><tr><th>Select</th><th>Product / activity</th><th>Outputs / evidence</th><th>Review</th></tr></thead><tbody>{visible.map((p:any)=><tr key={p.key}><td><input aria-label={'Publish '+p.profile.name+' '+p.profile.equipmentSet} type="checkbox" disabled={busy||Boolean(p.issues.length)||p.published} checked={selected.includes(p.key)} onChange={e=>{setSelected(values=>e.target.checked?[...values,p.key]:values.filter(k=>k!==p.key));setReviewed(false);}}/></td><td>{p.profile.product}{p.newProduct?<Badge>New product</Badge>:null}<br/>{p.profile.facility||'Facility missing'} · {p.profile.area} · {p.profile.context||'Context missing'}</td><td>{p.profile.outputs.map((o:any)=>o.name).join(', ')}<br/>{p.evidenceCount} source reports<br/>{p.profile.equipmentSet}</td><td>{p.published?'Already published':p.issues.length?p.issues.join(' '):'Ready for approval'}<details><summary>Locations and criteria</summary>{p.profile.outputs.map((o:any)=><div key={o.id}><strong>{o.name}</strong><ul>{o.instances.map((r:any,i:number)=><li key={i}>{r.label} · {r.location} {r.stage} {r.channel} · {r.criterion||'Criterion missing'} · {r.unit||'No unit'} · {r.date||'Date missing'}</li>)}</ul></div>)}</details></td></tr>)}</tbody></table></div><details className="spacing"><summary>Document exceptions ({preview.exceptions.length})</summary><ul>{preview.exceptions.map((e:any,i:number)=><li key={i}>{e.path}: {e.reason}</li>)}</ul></details><label className="checkbox spacing"><input type="checkbox" disabled={busy} checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I approve the selected products, locations, criteria, shared dates, facility/context defaults and assigned layouts.</label><button className="button primary" disabled={busy||!reviewed||!selected.length} onClick={publish}>Publish {selected.length} selected patterns</button></>:null}
 {results?<ul aria-label="Bulk publication results">{results.map((r:any)=><li key={r.key}>{r.name}: {r.status}{r.message?' — '+r.message:''}</li>)}</ul>:null}</details>;
}

/** Proposed locations are reviewed here; historical result cells are never imported. */
export function EnvironmentalPatterns({documents,templates,reload}:{documents:any[];templates:any[];reload:()=>void}){
 const {config,reload:reloadConfig}=useConfiguration(),notify=useContext(Notice);
 const {data:profiles,reload:reloadProfiles}=useLoad<EnvironmentalProfile[]>(()=>api('/environmental/profiles'));
 const [previous,setPrevious]=useState<EnvironmentalProfile>(),[source,setSource]=useState(''),[candidate,setCandidate]=useState<any>(),[hints,setHints]=useState<any>();
 const [name,setName]=useState(''),[productId,setProductId]=useState(''),[category,setCategory]=useState('EM'),[facility,setFacility]=useState(''),[area,setArea]=useState(''),[context,setContext]=useState(''),[equipmentSet,setEquipmentSet]=useState(''),[effectiveFrom,setEffectiveFrom]=useState(''),[effectiveTo,setEffectiveTo]=useState(''),[criterionDate,setCriterionDate]=useState('');
 const [outputs,setOutputs]=useState<EnvironmentalOutput[]>([]),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
 useUnsaved(Boolean(outputs.length||name));
 const products=config.value.products.filter(p=>p.active&&config.value.sampleTypes.some(t=>t.active&&t.id===p.category&&t.register==='environmental'));
 const changeOutput=(i:number,key:string,value:any)=>{setReviewed(false);setOutputs(rows=>rows.map((r,j)=>i===j?{...r,[key]:value}:r));};
 const changeRow=(oi:number,ri:number,key:string,value:string)=>{setReviewed(false);setOutputs(rows=>rows.map((o,j)=>j!==oi?o:{...o,instances:o.instances.map((r,k)=>k===ri?{...r,[key]:value}:r)}));};
 async function inspect(file:File){setBusy(true);setError('');setHints(undefined);setCandidate(undefined);try{const result=await api('/references/inspect','POST',{name:file.name,base64:await fileBase64(file)});setSource(result.id);setCandidate({sourceId:result.id,name:file.name,pattern:result.evidence.environmentalPattern});reload();if(!result.evidence.environmentalPattern)throw new Error('This document has no supported environmental table. Review its layout before creating a pattern.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function loadCandidate(){setBusy(true);setError('');setHints(undefined);try{const result=await api(`/references/${source}/environmental-pattern`);setCandidate(result);setHints(result.hints);const inferred=result.hints||{};const key=(value:string)=>value.normalize('NFKC').trim().toLocaleLowerCase();const product=products.find(p=>key(p.name)===key(inferred.product||'')||p.aliases.some(a=>key(a)===key(inferred.product||'')));const environmentType=config.value.sampleTypes.find(t=>t.active&&t.register==='environmental');const inferredCategory=config.value.sampleTypes.some(t=>t.id===inferred.category&&t.register==='environmental')?inferred.category:environmentType?.id||'EM';setProductId(product?.id||'');setCategory(product?.category||inferredCategory);setName([inferred.product,inferred.area].filter(Boolean).join(' — '));setFacility(inferred.facility||'');setArea(inferred.area||'');setContext(inferred.context||'');setEquipmentSet(inferred.equipmentSet||result.pattern.blocks.flatMap((b:any)=>b.instances||[]).map((r:any)=>r.location).filter(Boolean).filter((v:string,i:number,a:string[])=>a.indexOf(v)===i).join(', ').slice(0,195));setEffectiveFrom(inferred.effectiveFrom||'');setEffectiveTo(inferred.effectiveThrough||'');setReviewed(false);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function addDetectedProduct(){const name=String(hints?.product||'').trim(),type=config.value.sampleTypes.find(t=>t.active&&t.register==='environmental');if(!name||!type)return;setBusy(true);setError('');try{const existing=config.value.products.find(p=>p.active&&p.category===type.id&&p.name.trim().toLocaleLowerCase()===name.toLocaleLowerCase());if(existing){setProductId(existing.id);setCategory(existing.category);return;}const id=`product-${crypto.randomUUID()}`,value=structuredClone(config.value);value.products.push({id,name,code:'',category:type.id,aliases:[],active:true});await api('/configuration','PUT',{revision:config.revision,value});await reloadConfig();setProductId(id);setCategory(type.id);setReviewed(false);notify(`Added detected product: ${name}`);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 function addOutput(){
  if(!candidate?.pattern)return;
  const instances=candidate.pattern.blocks.flatMap((b:any)=>b.instances.map((r:any)=>({test:r.test,label:r.label,location:r.location,stage:r.stage||'',replicate:'',block:b.id,channel:r.channel,type:/negative|absent/i.test(r.criterion)?'finding':'numeric',unit:r.unit,criterion:/^[-\s]+$/.test(r.criterion)?'':r.criterion,source:candidate.sourceId,sourceLocation:r.sourceLocation,date:criterionDate,dateBasis:'owner-confirmed',revision:'owner-confirmed'})));
  const accupoint=instances.every((r:any)=>r.test==='ACCUPOINT');
  const proposedMode=/open[\s_-]*plate/i.test(candidate.name)?'open-plate':candidate.pattern.mode;
  let nextId=1;while(outputs.some(o=>o.id===`output${nextId}`))nextId++;setOutputs(rows=>[...rows,{id:`output${nextId}`,name:accupoint?'Accupoint surface monitoring':'SPC/MY monitoring',method:accupoint?'accupoint':candidate.pattern.mode==='gip'?'microbial':'spc-my',mode:proposedMode,templateId:'',templateRevision:'',instances}]);setReviewed(false);
 }
 function edit(profile:EnvironmentalProfile){setPrevious(profile);setName(profile.name);setProductId(profile.productId);setCategory(profile.category);setFacility(profile.facility);setArea(profile.area);setContext(profile.context);setEquipmentSet(profile.equipmentSet);setEffectiveFrom(profile.effectiveFrom);setEffectiveTo(profile.effectiveTo||'');setOutputs(structuredClone(profile.outputs));setReviewed(false);setError('');}
 function clear(){setPrevious(undefined);setName('');setProductId('');setFacility('');setArea('');setContext('');setEquipmentSet('');setEffectiveFrom('');setEffectiveTo('');setOutputs([]);setReviewed(false);}
 async function publish(){setBusy(true);setError('');try{const product=products.find(p=>p.id===productId);await api('/environmental/profiles','POST',{reviewed,previousId:previous?.id,revision:previous?.revision,profile:{name,productId,product:product?.name,category,facility,area,context,equipmentSet,effectiveFrom,effectiveTo:effectiveTo||undefined,evidenceIds:[...new Set(outputs.flatMap(o=>o.instances.map(r=>r.source)))],outputs}});notify('Approved sampling-pattern revision published');clear();reloadProfiles();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 return <section id="environmental-patterns" className="panel padded spacing" aria-label="Environmental sampling patterns"><h2>Environmental sampling patterns</h2><p>Confirm the product, process area and equipment set. Each monitoring output uses its own approved layout. The pattern supplies locations and criteria; analysts enter current results.</p><EnvironmentalBatch templates={templates} onPublished={()=>{reloadProfiles();reload();}}/>
 <div className="form-grid"><Field label="Inspect historical environmental DOCX"><input type="file" accept=".docx" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void inspect(file);e.target.value='';}}/></Field><Field label="Inspected pattern evidence"><select value={source} onChange={e=>{setSource(e.target.value);setCandidate(undefined);setHints(undefined);}}><option value="">Select a reference…</option>{documents.filter(d=>d.kind==='reference').map(d=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field></div><button className="button secondary small" disabled={!source||busy} onClick={loadCandidate}>Analyze locations and criteria</button>
 {candidate?.pattern?<div className="info spacing">{candidate.name} · {candidate.pattern.blocks.reduce((n:number,b:any)=>n+b.instances.length,0)} proposed test/location rows. Confirm criteria, units and monitoring mode below. Historical results and passing remarks are excluded.<div className="form-grid"><Field label="Confirmed criterion date"><input type="date" value={criterionDate} onChange={e=>setCriterionDate(e.target.value)}/></Field></div><button className="button secondary small" disabled={!criterionDate||busy} onClick={addOutput}>Add proposed monitoring output</button></div>:null}
 {hints?.product&&!productId?<div className="info spacing">Detected product: <strong>{hints.product}</strong>. It is missing from the managed environmental products.<button className="button secondary small" disabled={busy} onClick={addDetectedProduct}>Add detected product</button></div>:null}
 {hints?<div className="info spacing">Product, area, equipment/location group and effective start were prefilled from {hints.matchedActivity&&hints.sourceML?`matching logbook activity ${hints.sourceML}`:'the inspected report'}: {hints.equipmentSet||'sampling locations detected'}, received date {hints.effectiveFrom||'not available'}. Effective through is left open. Review the evidence match before publishing.</div>:null}
 <div className="form-grid spacing"><Field label="Pattern name"><input value={name} onChange={e=>{setName(e.target.value);setReviewed(false);}}/></Field><Field label="Managed environmental product"><select value={productId} onChange={e=>{setProductId(e.target.value);setCategory(products.find(p=>p.id===e.target.value)?.category||'EM');setReviewed(false);}}><option value="">Select product…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></Field>{[['Facility',facility,setFacility],['Process area',area,setArea],['Testing context',context,setContext],['Equipment set',equipmentSet,setEquipmentSet]] .map(([label,value,setter])=><Field key={String(label)} label={String(label)}><input value={String(value)} onChange={e=>{(setter as (v:string)=>void)(e.target.value);setReviewed(false);}}/></Field>)}<Field label="Effective from"><input type="date" value={effectiveFrom} onChange={e=>{setEffectiveFrom(e.target.value);setReviewed(false);}}/></Field><Field label="Effective through (optional)"><input type="date" value={effectiveTo} onChange={e=>{setEffectiveTo(e.target.value);setReviewed(false);}}/></Field></div>
 {outputs.map((output,oi)=><div className="spacing" key={oi}><div className="section-heading"><h3>Output {oi+1}</h3><button className="button secondary small" disabled={busy} onClick={()=>{setOutputs(rows=>rows.filter((_,i)=>i!==oi));setReviewed(false);}}>Remove output {oi+1}</button></div><div className="form-grid"><Field label={`Output ${oi+1} name`}><input value={output.name} onChange={e=>changeOutput(oi,'name',e.target.value)}/></Field><Field label="Monitoring method"><select value={output.method} onChange={e=>changeOutput(oi,'method',e.target.value)}><option value="spc-my">SPC / Molds and Yeast</option><option value="accupoint">Accupoint</option><option value="microbial">Microbial panel (GIP)</option></select></Field><Field label="Monitoring mode"><select value={output.mode} onChange={e=>changeOutput(oi,'mode',e.target.value)}><option value="surface">Surface</option><option value="open-plate">Open plate</option><option value="water-validation">Water validation</option><option value="gip">GIP</option><option value="phase-air">Warehouse phase / air</option></select></Field><Field label="Approved report layout"><select value={output.templateId} onChange={e=>{const t=templates.find(t=>t.id===e.target.value);setOutputs(rows=>rows.map((r,j)=>j===oi?{...r,templateId:t?.id||'',templateRevision:t?.revision||''}:r));setReviewed(false);}}><option value="">Select layout…</option>{templates.filter(t=>t.category===category&&t.verified&&t.active!==false).map(t=><option key={t.id} value={t.id}>{t.name} · {t.revision.slice(0,8)}</option>)}</select></Field></div>
 <div className="table-scroll"><table><caption>Confirm every sampling location and criterion for {output.name}</caption><thead><tr><th>Test</th><th>Location</th><th>Stage / replicate</th><th>Criterion / unit</th><th>Criterion date</th><th>Evidence</th></tr></thead><tbody>{output.instances.map((row,ri)=><tr key={ri}><td><Field label={`Row ${ri+1} test`}><select value={row.test} onChange={e=>{changeRow(oi,ri,'test',e.target.value);changeRow(oi,ri,'label',config.value.tests.find(t=>t.id===e.target.value)?.reportLabel||e.target.value);}}><option value="">Confirm test…</option>{config.value.tests.filter(t=>t.active&&t.categories.includes(category)).map(t=><option key={t.id} value={t.id}>{t.reportLabel||t.name}</option>)}</select></Field></td><td><Field label={`Row ${ri+1} location`}><input value={row.location} onChange={e=>changeRow(oi,ri,'location',e.target.value)}/></Field></td><td><Field label={`Row ${ri+1} stage`}><input value={row.stage} onChange={e=>changeRow(oi,ri,'stage',e.target.value)}/></Field>{row.channel?<Field label={`Row ${ri+1} air channel`}><select value={row.channel} onChange={e=>changeRow(oi,ri,'channel',e.target.value)}><option value="active-air">Active air</option><option value="passive-air">Passive air</option></select></Field>:null}<Field label={`Row ${ri+1} replicate`}><input value={row.replicate} onChange={e=>changeRow(oi,ri,'replicate',e.target.value)}/></Field></td><td><Field label={`Row ${ri+1} criterion`}><input value={row.criterion} onChange={e=>changeRow(oi,ri,'criterion',e.target.value)}/></Field><Field label={`Row ${ri+1} unit`}><input value={row.unit} onChange={e=>changeRow(oi,ri,'unit',e.target.value)}/></Field></td><td><Field label={`Row ${ri+1} criterion date`}><input type="date" value={row.date} onChange={e=>changeRow(oi,ri,'date',e.target.value)}/></Field></td><td><small>{documents.find(d=>d.id===row.source)?.name||row.source}<br/>{row.sourceLocation}<br/>Block: {row.block}</small></td></tr>)}</tbody></table></div></div>)}
 <label className="checkbox spacing"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)}/>I reviewed all locations, criteria, dates, units, monitoring modes and layouts against the evidence.</label><ErrorBox message={error}/><div className="inline-form"><button className="button primary" disabled={busy||!reviewed||!outputs.length} onClick={publish}>{previous?'Publish new pattern revision':'Publish approved pattern'}</button>{previous||outputs.length?<button className="button secondary" disabled={busy} onClick={clear}>Discard pattern edits</button>:null}</div>
 <h3 className="spacing">Approved patterns</h3>{profiles?.map(p=><div className="file-row" key={p.id}><div><strong>{p.name}</strong><small>{p.product} · {p.facility} · {p.area} · {p.equipmentSet}<br/>{p.effectiveFrom}{p.effectiveTo?` → ${p.effectiveTo}`:''} · {p.outputs.map(o=>o.name).join(', ')} · {p.revision.slice(0,8)}</small></div><Badge>{p.active?'Active':'Retired'}</Badge>{p.active?<><button className="button secondary small" disabled={busy} onClick={()=>edit(p)}>Revise</button><button className="button secondary small" disabled={busy} onClick={async()=>{setBusy(true);setError('');try{await api(`/environmental/profiles/${p.id}/retire`,'PATCH',{revision:p.revision});reloadProfiles();}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>Retire</button></>:null}</div>)}
 </section>;
}
