import Dialog from './dialog';
import {useContext,useEffect,useState} from 'react';
import {FileText,RefreshCw,ArrowUpRight} from 'lucide-react';
import {api} from './api';
import {PageTitle,useLoad,Notice,Session,SearchInput,ErrorBox,Loading,Empty,Badge} from './ui';
export default function FileLibrary(){
 const [q,setQ]=useState(''),[search,setSearch]=useState(''),[kind,setKind]=useState(''),[sort,setSort]=useState('numeric'),[page,setPage]=useState(1),[busy,setBusy]=useState(false),[preview,setPreview]=useState<any>();
 const notify=useContext(Notice),{user}=useContext(Session);
 useEffect(()=>{const t=setTimeout(()=>{setSearch(q);setPage(1);},250);return()=>clearTimeout(t);},[q]);
 const params=new URLSearchParams({q:search,kind,sort,page:String(page)});const {data,error,reload}=useLoad(()=>api('/library-items?'+params),[params.toString()]);
 return <><PageTitle title="Files & documents" description="Find generated reports, historical references and authorized library files." action={user.role==='administrator'?<button className="button secondary" disabled={busy} onClick={async()=>{setBusy(true);try{const r=await api('/library/sync','POST');notify(`Library refreshed: ${r.count} files`);reload();}catch(e:any){notify(e.message,true);}finally{setBusy(false);}}}><RefreshCw size={17}/>{busy?'Refreshing…':'Refresh library'}</button>:undefined}/><section className="panel"><div className="filters"><SearchInput value={q} onChange={setQ} placeholder="Find a document or control number…"/><select aria-label="Document type" value={kind} onChange={e=>{setKind(e.target.value);setPage(1);}}><option value="">All documents</option><option value="report">Generated reports</option><option value="reference">Historical references</option><option value="template-candidate">Prepared templates</option><option value="library">Drive library</option></select><select aria-label="Document order" value={sort} onChange={e=>{setSort(e.target.value);setPage(1);}}><option value="numeric">Identifier / numeric order ↑</option><option value="recent">Newest first</option></select></div><ErrorBox message={error}/>{!data?<Loading/>:data.items.length?<>{data.items.map((f:any)=><div className="file-row" key={f.id}><FileText size={24}/><div className="sample-main"><strong>{f.name}</strong><small>{{report:'Generated report',reference:'Historical reference','template-candidate':'Prepared template',library:'Authorized Drive file'}[f.kind as string]||'Document'}{f.resultRevision?` · Result revision ${f.resultRevision}`:''}</small>{f.externalReviewRequired?<Badge tone="amber">External review required</Badge>:null}</div>{f.hasPreview?<button className="button secondary small" onClick={()=>setPreview(f)}>Preview</button>:null}{f.sourceUrl?<a className="button secondary small" href={f.sourceUrl} target="_blank" rel="noreferrer">Open in Drive <ArrowUpRight size={14}/></a>:<a className="button secondary small" href={`/api/files/${f.id}/download`}>Download</a>}</div>)}<div className="pagination"><span>{data.total} documents · Page {data.page} of {Math.max(1,Math.ceil(data.total/data.limit))}</span><button className="button secondary small" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><button className="button secondary small" disabled={page*data.limit>=data.total} onClick={()=>setPage(p=>p+1)}>Next</button></div></>:<Empty title={q||kind?'No documents match these filters':'Your documents will appear here'}>Generate a report or ask an administrator to connect an authorized library folder.</Empty>}</section>{preview?<Dialog title={preview.name} onClose={()=>setPreview(undefined)} wide><iframe title="Document preview" src={`/api/files/${preview.id}/preview`}/></Dialog>:null}</>;
}
