import {useContext,useState} from 'react';
import {api} from './api';
import {useConfiguration,useUnsaved} from './configuration';
import {useLoad,Field,ErrorBox,Notice,Badge,Empty} from './ui';
import type {Specification,Criterion} from '../shared/model';
export default function Specifications(){
 const {config}=useConfiguration();const {data,reload}=useLoad(()=>api('/references'));const [edit,setEdit]=useState<Specification|null>(null),[q,setQ]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false);const notify=useContext(Notice);useUnsaved(!!edit);
 const patch=(key:string,value:any)=>setEdit(e=>e?{...e,[key]:value}:e);
 const testPatch=(i:number,key:string,value:string)=>patch('tests',edit!.tests.map((t,j)=>i===j?{...t,[key]:value}:t));
 return <section className="panel padded"><div className="section-heading"><div><h2>Specifications</h2><p>Applicable tests and acceptance criteria. Actual results are entered separately.</p></div><button className="button primary" onClick={()=>setEdit({id:'',product:'',category:config.value.sampleTypes[0].id,context:'',revision:'',tests:[],issues:[],source:'',active:true})}>Add specification</button></div><ErrorBox message={error}/><input aria-label="Search specifications" placeholder="Find a product or testing context…" value={q} onChange={e=>setQ(e.target.value)}/>
 {!edit?data?.specifications.filter((s:Specification)=>`${s.product} ${s.context}`.toLowerCase().includes(q.toLowerCase())).map((s:Specification)=><button className="user-row" key={s.id} onClick={()=>setEdit(structuredClone(s))}><span><strong>{s.product}</strong><small>{s.context} · {s.tests.length} tests</small></span><Badge>{s.active===false?'Inactive':'Active'}</Badge><span>Edit revision</span></button>):<form className="spacing" onSubmit={async e=>{e.preventDefault();if(!window.confirm('Save a new specification revision? Existing drafts and reports will keep their previous criteria.'))return;setBusy(true);setError('');try{await api('/specifications','POST',edit);setEdit(null);reload();notify('Specification revision saved. Existing reports are unchanged.');}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>
 <div className="form-grid"><Field label="Product / material"><select required value={`${edit.category}|${edit.product}`} onChange={e=>{const p=config.value.products.find(p=>`${p.category}|${p.name}`===e.target.value);if(p)setEdit({...edit,product:p.name,category:p.category});}}><option value="">Choose a managed product…</option>{edit.product&&!config.value.products.some(p=>p.name===edit.product)?<option value={`${edit.category}|${edit.product}`}>{edit.product}</option>:null}{config.value.products.filter(p=>p.active).map(p=><option key={p.id} value={`${p.category}|${p.name}`}>{p.name}</option>)}</select></Field><Field label="Testing context"><input required value={edit.context} onChange={e=>patch('context',e.target.value)}/></Field><Field label="Availability"><select value={String(edit.active!==false)} onChange={e=>patch('active',e.target.value==='true')}><option value="true">Active</option><option value="false">Inactive — preserve history</option></select></Field><Field label="Reference document"><select required value={edit.source} onChange={e=>patch('source',e.target.value)}><option value="">Choose inspected source…</option>{edit.source&&!data?.documents.some((d:any)=>d.id===edit.source)?<option value={edit.source}>{edit.source}</option>:null}{data?.documents.filter((d:any)=>d.kind==='reference').map((d:any)=><option key={d.id} value={d.id}>{d.name}</option>)}</select></Field></div>
 {edit.tests.map((t,i)=><div className="test-card" key={i}><div className="section-heading"><h3>{t.label||'Applicable test'}</h3><button type="button" className="text-button" onClick={()=>patch('tests',edit.tests.filter((_,j)=>j!==i))}>Remove from this revision</button></div><div className="form-grid"><Field label="Test"><select required value={t.test} onChange={e=>{const x=config.value.tests.find(x=>x.id===e.target.value)!;patch('tests',edit.tests.map((t,j)=>j===i?{...t,test:x.id,label:x.reportLabel,unit:x.unit,type:x.inputType}:t));}}><option value="">Choose test…</option>{config.value.tests.filter(t=>t.active&&t.categories.includes(edit.category)).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></Field>{[['criterion','Acceptance criterion'],['unit','Unit'],['sourceLocation','Source page / table / row'],['location','Container / location'],['stage','Testing stage'],['replicate','Replicate']].map(([key,label])=><Field key={key} label={label}><input required={['criterion','sourceLocation'].includes(key)} value={(t as any)[key]||''} onChange={e=>testPatch(i,key,e.target.value)}/></Field>)}<Field label="Explicit source date"><input required type="date" value={t.date} onChange={e=>testPatch(i,'date',e.target.value)}/></Field><Field label="Date basis"><select value={t.dateBasis} onChange={e=>testPatch(i,'dateBasis',e.target.value)}><option value="release">Release date</option><option value="analysis">Analysis date (no release date)</option></select></Field></div></div>)}
 <div className="actions"><button type="button" className="button secondary" onClick={()=>patch('tests',[...edit.tests,{test:'',label:'',type:'numeric',unit:'',criterion:'',source:edit.source,sourceLocation:'',date:'',dateBasis:'release',revision:''} as Criterion])}>Add applicable test</button><button type="button" className="button secondary" disabled={busy} onClick={()=>setEdit(null)}>Cancel</button><button className="button primary" disabled={busy||!edit.tests.length}>{busy?'Saving…':'Save new revision'}</button></div></form>}
 {!data?.specifications.length&&!edit?<Empty title="No specifications yet">Add a product, inspect its reference document, then define its applicable tests and criteria.</Empty>:null}</section>;
}
