import {useCatalog,useUnsaved} from './configuration';
import {useContext,useState} from 'react';
import {FileText,Upload} from 'lucide-react';
import {api,fileBase64} from './api';
import {PageTitle,useLoad,Notice,Field,ErrorBox,Badge} from './ui';
import {type Category} from '../shared/model';

type Binding={index:number;test:string;location:string;stage:string;replicate:string};
export default function TemplatesPage(){const {categories,testLabels}=useCatalog();
 const {data,reload}=useLoad(()=>api('/references'));
 const [source,setSource]=useState(''),[prepared,setPrepared]=useState<any>();
 const [file,setFile]=useState<File>(),[name,setName]=useState(''),[category,setCategory]=useState<Category>('FG'),[family,setFamily]=useState('routine');
 const [required,setRequired]=useState('analysisDate, logbookReference'),[bindings,setBindings]=useState<Binding[]>([]);
 const [sanitized,setSanitized]=useState(false),[verified,setVerified]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const notify=useContext(Notice);
 const update=(i:number,k:keyof Binding,value:string)=>setBindings(rows=>rows.map((r,j)=>i===j?{...r,[k]:value}:r));
 async function prepare(){setBusy(true);setError('');try{const r=await api(`/references/${source}/prepare-template`,'POST');setPrepared(r);setFile(undefined);setName(r.name.replace(/^Prepared · /,''));setFamily(data?.documents?.find((x:any)=>x.id===source)?.evidenceSummary?.family||'routine');setRequired((r.manifest.requiredFields||[]).join(', '));setBindings((r.manifest.instances||[]).map((x:any)=>({index:x.index,test:'',location:'',stage:'',replicate:''})));setSanitized(false);setVerified(false);reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function register(){setBusy(true);setError('');try{await api('/references/templates','POST',{name,category,family,...(prepared?{preparedId:prepared.id}:{base64:await fileBase64(file!)}),sanitized,layoutVerified:verified,requiredFields:required.split(',').map(x=>x.trim()).filter(Boolean),resultBindings:bindings});notify('Standardized template registered');setPrepared(undefined);setFile(undefined);setBindings([]);reload();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 const issues=prepared?.manifest.issues||[];
 return <><section className="panel padded"><h2>Prepare the repeated report layout</h2><p>Choose an inspected historical DOCX. The workspace copies its page layout and replaces recognized sample fields, criteria and results with blank placeholders. Check the prepared copy before using it.</p><div className="inline-form"><select aria-label="Inspected report" value={source} onChange={e=>setSource(e.target.value)}><option value="">Choose an inspected report…</option>{data?.documents?.filter((x:any)=>x.kind==='reference').map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select><button className="button secondary" disabled={!source||busy} onClick={prepare}>Prepare copy</button></div>{prepared?<div className="spacing"><a className="button secondary" href={`/api/files/${prepared.id}/download`}><FileText size={16}/> Download prepared DOCX for layout review</a><p className="muted">The source report remains untouched. Confirm each numbered table row below before registration.</p>{issues.length?<div className="error">Preparation needs review: {issues.join('; ')}</div>:null}{prepared.manifest.instances.map((x:any,i:number)=><div className="test-card" key={i}><h3>Document row {i+1}: {x.label||'(container or location row)'}</h3><p>Historical criterion: {x.originalCriterion}</p><div className="form-grid"><Field label="Applicable test"><select value={bindings[i]?.test||''} onChange={e=>update(i,'test',e.target.value)}><option value="">Confirm test…</option>{Object.entries(testLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field>{(['location','stage','replicate'] as const).map(k=><Field label={k} key={k}><input value={bindings[i]?.[k]||''} onChange={e=>update(i,k,e.target.value)} placeholder={k==='location'?x.label:''}/></Field>)}</div></div>)}</div>:null}</section>
 <section className="panel padded spacing"><h2>Register a standardized template</h2><p>Use the prepared copy above, or upload a blank DOCX with a repeating test row. Keep the approved page geometry, form text, tables, headers and footers.</p><div className="form-grid"><Field label="Template name"><input value={name} onChange={e=>setName(e.target.value)}/></Field><Field label="Category"><select value={category} onChange={e=>setCategory(e.target.value as Category)}>{Object.entries(categories).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></Field><Field label="Report family"><select value={family} onChange={e=>setFamily(e.target.value)}>{['routine','raw-material-packaging','stability','container-location','water','environmental'].map(f=><option key={f}>{f}</option>)}</select></Field><Field label="Required field names"><input value={required} onChange={e=>setRequired(e.target.value)}/></Field></div><Field label="Blank DOCX upload (only when not using a prepared copy)"><input type="file" accept=".docx" disabled={!!prepared} onChange={e=>setFile(e.target.files?.[0])}/></Field><label className="checkbox"><input type="checkbox" checked={sanitized} onChange={e=>setSanitized(e.target.checked)}/>I checked that historical sample identifiers, results, passing remarks, dates and signatures are absent.</label><label className="checkbox"><input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/>I visually checked the DOCX against the standardized reference, including pagination.</label><ErrorBox message={error}/><button className="button primary" disabled={busy||!name||!(prepared||file)||!sanitized||!verified||issues.length>0||bindings.some(x=>!x.test)} onClick={register}><Upload size={16}/> Register template</button></section>
 <section className="panel padded spacing"><h2>Template revisions</h2>{data?.templates?.map((t:any)=><div className="file-row" key={t.id}><FileText size={20}/><div><strong>{t.name}</strong><small>{t.family} · {categories[t.category as Category]} · {t.revision.slice(0,12)}</small></div><Badge tone="green">Verified</Badge></div>)}</section></>;
}
