import {useCatalog,useUnsaved,useConfiguration} from './configuration';
import {cloneElement,createContext,isValidElement,useContext,useEffect,useId,useState,type ReactNode} from 'react';
import {Link,useLocation} from 'react-router-dom';
import {ArrowUpRight,FlaskConical,Search,FileText,Table2,FolderOpen,Bot,Settings,ClipboardList,Activity,HelpCircle,Columns3} from 'lucide-react';
import type {Sample,User} from '../shared/model';

export const Session=createContext<{user:User;demo:boolean}>({user:{email:'',name:'',role:'viewer'},demo:false});
export const Notice=createContext<(message:string,error?:boolean)=>void>(()=>{});
export function useLoad<T>(fetcher:()=>Promise<T>,deps:unknown[]=[]){const [data,setData]=useState<T>(),[error,setError]=useState(''),[version,setVersion]=useState(0);useEffect(()=>{const refresh=()=>setVersion(v=>v+1);window.addEventListener('ipi:sync-complete',refresh);return()=>window.removeEventListener('ipi:sync-complete',refresh);},[]);useEffect(()=>{let active=true;setError('');setData(undefined);fetcher().then(d=>{if(active)setData(d);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[...deps,version]);return {data,setData,error,reload:()=>setVersion(v=>v+1)};}
export function LabMotionMark({path}:{path:string}){return <svg className="page-motion-mark" viewBox="0 0 72 72" aria-hidden="true" focusable="false"><circle className="page-motion-dish" cx="36" cy="36" r="32"/><circle className="page-motion-rim" cx="36" cy="36" r="30.5"/><circle className="page-motion-agar" cx="36" cy="36" r="24.5"/><ellipse className="page-motion-scan" cx="36" cy="36" rx="24.5" ry="9"/><g className="page-motion-colonies"><circle cx="25" cy="26" r="2.3"/><circle cx="46" cy="23" r="1.5"/><circle cx="48" cy="43" r="2.7"/><circle cx="31" cy="48" r="1.7"/><circle cx="20" cy="39" r="1.2"/></g><path className="page-motion-line" pathLength="100" d={path}/><circle className="page-motion-node" cx="36" cy="36" r="2.5"/><circle className="page-motion-signal" cx="58" cy="36" r="2"/></svg>;}
export function PageTitle({eyebrow,title,description,action}:{eyebrow?:string;title:string;description:string;action?:ReactNode}){
  const {pathname}=useLocation();
  const Icon=pathname==='/new'?FlaskConical:pathname.startsWith('/samples/')?ClipboardList:pathname==='/samples'?Search:pathname.startsWith('/worksheet')?Table2:pathname.startsWith('/reports')?FileText:pathname.startsWith('/library')?FolderOpen:pathname.startsWith('/assistant')?Bot:pathname.startsWith('/shared')?Columns3:pathname.startsWith('/settings')?Settings:pathname==='/'?Activity:HelpCircle;
  return <div className="page-heading"><div className="page-title-mark" aria-hidden="true"><Icon size={26} strokeWidth={1.7}/></div><div className="page-heading-copy"><h1>{title}</h1>{eyebrow?<div className="record-heading-id">{eyebrow}</div>:null}<p>{description}</p></div>{action?<div className="page-heading-action">{action}</div>:null}</div>;
}
export function Empty({title,children}:{title:string;children?:ReactNode}){return <div className="empty"><FlaskConical size={32}/><h3>{title}</h3><p>{children}</p></div>;}
export function ErrorBox({message}:{message:string}){return message?<div className="error" role="alert">{message}</div>:null;}
export function Loading(){return <div className="loading-state" role="status" aria-live="polite"><div className="loading-orbit" aria-hidden="true"><FlaskConical/><i/><i/><i/></div><strong>Preparing your workspace</strong><span className="typing-status">Checking samples and records</span></div>;}
export function Badge({children,tone='neutral'}:{children:ReactNode;tone?:string}){return <span className={`badge ${tone}`}>{children}</span>;}
const analystNames=[
  {fullName:'Roy Vincent Codiñera',aliases:['Roy']},
  {fullName:'James Bryle A. Goloran',aliases:['James']},
  {fullName:'Jasmin C. Barangan',aliases:['Jas']},
  {fullName:'Ahrianne B. Canoy',aliases:['Ahrianne','Aryan']},
  {fullName:'Annaleen C. Villaver',aliases:['Annaleen','Anne']},
  {fullName:'Daryl Chris D. Nueva',aliases:['Daryl']},
];
function fullAnalystName(value:string){const normalized=value.trim().toLocaleLowerCase();return analystNames.find(({fullName,aliases})=>[fullName,...aliases].some(name=>name.toLocaleLowerCase()===normalized))?.fullName||value;}
export function Field({label,children,hint}:{label:string;children:ReactNode;hint?:string}){const labelId=useId();const analystField=label==='Analyst display name'&&isValidElement(children);const control=analystField?cloneElement(children as React.ReactElement<any>,{list:'analyst-name-options',autoComplete:'off',placeholder:'Search by first name or nickname',onChange:(event:React.ChangeEvent<HTMLInputElement>)=>{const value=fullAnalystName(event.target.value);(children.props as any).onChange?.({...event,target:{...event.target,value}});}}):children;const namedControl=isValidElement(control)&&['input','select','textarea'].includes(control.type as string)?cloneElement(control as React.ReactElement<any>,{'aria-labelledby':labelId}):control;return <label className="field"><span id={labelId}>{label}</span>{namedControl}{analystField?<datalist id="analyst-name-options">{analystNames.flatMap(({fullName,aliases})=>[<option key={fullName} value={fullName}>{aliases[0]}</option>,...aliases.map(alias=><option key={`${fullName}-${alias}`} value={alias}>{fullName}</option>)])}</datalist>:null}{hint?<small>{hint}</small>:null}</label>;}
export function SampleList({samples}:{samples:Sample[]}){const {categories,testLabels}=useCatalog();return samples.length?<div className="sample-list">{samples.map(s=><Link className="sample-row" to={`/samples/${s.id}`} key={s.id}><div className="sample-icon"><FlaskConical size={20}/></div><div className="sample-main"><span className="mono muted">{s.ml}</span><strong>{s.name||'Incomplete source record'}</strong><span className="muted">{categories[s.category]} · Batch {s.batch||'not entered'}</span></div><div className="sample-meta"><Badge tone={s.status==='RELEASED'?'green':'amber'}>{s.status||'Not recorded'}</Badge>{s.duplicate?<Badge tone="red">Duplicate ML</Badge>:null}<small>{s.source.sheet}</small></div><ArrowUpRight size={18}/></Link>)}</div>:<Empty title="No samples found">Try another search or connect your logbook in Settings.</Empty>;}
export function SearchInput({value,onChange,placeholder='Search ML number, product or batch…'}:{value:string;onChange:(v:string)=>void;placeholder?:string}){return <div className="search search-field"><Search size={18}/><input aria-label={placeholder} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/></div>;}
export function useCanEdit(){return useContext(Session).user.role!=='viewer';}
